### ISSUE TITLE
deleteBeforeReplace not being honored in Go - resources with persistent elements cannot be upgraded

### ISSUE THREAD

**Issue by dcaba** [pulumi/pulumi-gcp#132] opened 2019-04-06 00:00 UTC
Hello,

trying to create an instance with a static IP, I'm afraid I've found out updating some parameters (like the startup script) becomes impossible as the [deleteBeforeReplace that is stated in the docs](https://pulumi.io/reference/programming-model.html#deletebeforereplace) is not honored. 

Given this code:
```go
func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		const instancePrefix = "remove-me-when-upgrading"

		staticIP, err := compute.NewAddress(ctx, instancePrefix+"-ip", &compute.AddressArgs{})

		instanceConfig := &compute.InstanceArgs{
			MachineType: "f1-micro",
			BootDisk: map[string]interface{}{
				"initializeParams": map[string]string{
					"image": "ubuntu-os-cloud/ubuntu-minimal-1804-bionic-v20190403",
				},
			},
			MetadataStartupScript:  "echo " + time.Now().String(),
			AllowStoppingForUpdate: true,
			NetworkInterfaces: []interface{}{
				map[string]interface{}{
					"network": "default",
					"accessConfigs": []map[string]interface{}{
						map[string]interface{}{
							"natIp": staticIP.Address(),
						},
					},
				},
			},
		}

		_, err = compute.NewInstance(ctx, instancePrefix, instanceConfig, pulumi.ResourceOpt{
			DeleteBeforeReplace: true,
		})
		return err
	})
}
```
First execution is successful:
```
Updating (dev):

     Type                     Name                         Status      
 +   pulumi:pulumi:Stack      pulumiExample-dev            created     
 +   ├─ gcp:compute:Address   remove-me-when-upgrading-ip  created     
 +   └─ gcp:compute:Instance  remove-me-when-upgrading     created     
 
Resources:
    + 3 created

Duration: 57s
```
But the second (that brings a change in the startup script) cannot be applied:
```
 $ pulumi up
Previewing update (dev):

     Type                     Name                      Plan        Info
     pulumi:pulumi:Stack      pulumiExample-dev                     
 +-  └─ gcp:compute:Instance  remove-me-when-upgrading  replace     [diff: ~metadataStartupScript,name]
 
Resources:
    +-1 to replace
    2 unchanged

Do you want to perform this update? yes
Updating (dev):

     Type                     Name                      Status                   Info
     pulumi:pulumi:Stack      pulumiExample-dev         **failed**               1 error
 +-  └─ gcp:compute:Instance  remove-me-when-upgrading  **replacing failed**     [diff: ~metadataStartupScript,name]; 1 error
 
Diagnostics:
  pulumi:pulumi:Stack (pulumiExample-dev):
    error: update failed
 
  gcp:compute:Instance (remove-me-when-upgrading):
    error: Plan apply failed: Error creating instance: googleapi: Error 400: Invalid resource usage: 'External IP address: 35.205.71.221 is already in-use.'., invalidResourceUsage
 
Resources:
    2 unchanged

Duration: 3s
```
Changing the value of `DeleteBeforeReplace` does not affect to the execution plan, while the expectation is the instance being removed first so a new one becomes attached to the original static IP.

Execution environment:
* Sample source code: [gist](https://gist.github.com/dcaba/d2f19f74dd9646f121d20d206bc4bb56)
* Client version:
```
$ pulumi version
v0.17.4
```
* Plugin version:
```
$ pulumi plugin ls
NAME  KIND      VERSION  SIZE   INSTALLED  LAST USED
gcp   resource  0.18.2   64 MB  n/a        15 hours ago
gcp   resource  0.16.8   61 MB  n/a        15 hours ago
```
* Go version:
```
$ go version
go version go1.12.2 linux/amd64
```

**Comment by lukehoban** [comment] 2020-01-15 06:07
Dupe of https://github.com/pulumi/pulumi/issues/3513 which was fixed recently.

**Closed by lukehoban** 2020-01-15 06:07 UTC
Labels: help wanted
