### ISSUE TITLE
Reference to terraform in pulumi GCP bucket docs

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-gcp#1945] opened 2024-04-23 11:56 UTC
### What happened?

https://www.pulumi.com/registry/packages/gcp/api-docs/storage/bucket/#effectivelabels_yaml refers to Terraform:

```
All of labels (key/value pairs) present on the resource in GCP, including the labels configured through Terraform, other clients and services.
```

It should say Pulumi instead.

### Example

.

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment] 2024-04-26 16:26
Duplicate of https://github.com/pulumi/pulumi-gcp/issues/1473.

**Closed by iwahbe** 2024-04-26 16:26 UTC
Labels: area/docs, kind/bug, resolution/duplicate
