### ISSUE TITLE
gcp.storage.BucketObject does not refresh an object if using the source parameter instead of content

### ISSUE THREAD

**Issue by sylv3r** [pulumi/pulumi-gcp#87] opened 2019-01-29 02:00 UTC
Discussion on this matter with @clstokes on slack here : https://pulumi-community.slack.com/archives/C84L4E3N1/p1548693619818500

### Problem

When creating an object with the `source` parameter on a `gcp.storage.BucketObject` pulumi (or the provider) does not detect a change on the local file and thus does not update the related bucket object.

### How to reproduce

1. Create an object in a gcp bucket referencing a local file : 
```
new gcp.storage.BucketObject('my-object', {
  bucket: 'bucket-name',
  name: 'my-object',
  source: 'absolute/path/to/file.ext',
});
```
2. `pulumi up` succeeds to create the object in the bucket
3. Update the local file content (name and path stay unchanged, only the md5 is different)
4. Run `pulumi up` again -> no change detected

**Comment by joeduffy** [comment] 2019-01-29 20:51
This definitely seems like a bug where we're accepting a `string` when only an `Archive` should be allowed. This would explain the odd diffing behavior.

**Comment by sylv3r** [comment] 2019-02-10 01:49
@joeduffy Ok, I see what you mean when looking into the method documentation.
 
How one is supposed to create/use an `Archive` in this case instead of a `string` then ?

Couldn't you accept a `string` and make an automatically create an `Archive` (whatever that is) from it under the hood to handle this simple case ?

**Comment by clstokes** [comment] 2019-02-12 00:02
Per an internal conversation, `source` should be retyped to `Asset` rather than `Archive`. This should achieve the correct/expected behavior.

**Comment by lukehoban** [comment] 2019-02-12 04:24
See also https://github.com/pulumi/pulumi/issues/280 which is sort of a root cause here.

**Comment by lukehoban** [comment] 2019-02-28 20:31
We should do a sweep of `source` properties that map to files on disk and ensure we have mapped them to `Assets`/`Archives`.  It was raised recently that `aws.lambda.Layer` has a similar problem (we addressed this for `aws.lambda.Function` a long time ago).  We'll also need to come up with a general strategy here on two fronts:
1. How to make the change from `source: string` to `something: Asset`
2. How to decide whether to accept `Asset` or `Archive`, and ideally how to ensure that we don't have to make this decision at all by fixing https://github.com/pulumi/pulumi/issues/280.

Given how many commonly used APIs this impacts, would be great to tackle these sooner than later.

**Comment by jen20** [comment] 2019-03-09 00:30
This is fixed in #101, but we likely don't want to release it until after #106 is considered OK to go out, since it represents a breaking type change. Consequently, I'll move this to M22.

**Comment by jen20** [comment] 2019-06-01 14:31
This seems dependent on pulumi/pulumi#280, which is not currently assigned. For now I'll remove this from a milestone, though #101 should fix this when pulumi/pulumi#280 is dealt with.

**Closed** 2019-08-27 16:18 UTC
Labels: feature/q3
