### ISSUE TITLE
In container.Cluster, setting maintenancePolicy.dailyMaintenanceWindow.duration causes an error

### ISSUE THREAD

**Issue by q42jaap** [pulumi/pulumi-gcp#457] opened 2020-10-08 11:45 UTC
I'm getting the following error when I try to create/update a gke cluster with `maintenancePolicy.dailyMaintenanceWindow.duration` set.

```
Diagnostics:
  gcp:container:Cluster (cluster):
    error: gcp:container/cluster:Cluster resource 'cluster' has a problem: "maintenance_policy.0.daily_maintenance_window.0.duration": this field cannot be set
```

The code I'm running:
```
new container.Cluster("cluster", {
	project: config.project,
	name: config.clusterName,
	network: config.networkName,
	location: config.region,
	initialNodeCount: 1,
	maintenancePolicy: {
		dailyMaintenanceWindow: {
			startTime: "10:00",
			duration: "7h",
		},
	},
...
}
```

When I comment out `duration` the cluster will create/update just fine.

**Comment by mikhailshilkov** [comment] 2023-01-30 14:33
I gave it a quick try today and got a different but similar error:

> Value for unconfigurable attribute: Can't configure a value for "maintenance_policy.0.daily_maintenance_window.0.duration": its value will be decided automatically based on the result of applying this configuration

It sounds like `duration` is effectively read-only by design, so I'll close the issue as such.

**Closed by mikhailshilkov** 2023-01-30 14:33 UTC
Labels: kind/bug, resolution/by-design
