### ISSUE TITLE
GO, gcp container

### ISSUE THREAD

**Issue by henres** [pulumi/pulumi-gcp#342] opened 2020-05-13 13:56 UTC
Hello,

I have an error with the golang package version 3.4.0.
When I want to use container part, it failed :
```go
// main.go
package main

import (
	"github.com/pulumi/pulumi-gcp/sdk/v3/go/gcp/storage"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		_, err := container.NewCluster(ctx, "mon-cluster-de-test",
			&container.ClusterArgs{
				Location: pulumi.String("europe-west1-b"),
			},
			nil,
		)
		if err != nil {
			return err
		}

		return nil
	})
}
```

```bash
$ pulumi up
Previewing update (dev):
     Type                 Name            Plan     Info
     pulumi:pulumi:Stack  pulumi-poc-dev           1 error; 20 messages
 
Diagnostics:
  pulumi:pulumi:Stack (pulumi-poc-dev):
    error: an unhandled error occurred: program exited with non-zero exit code: 1
 
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xabcf30]
    goroutine 1 [running]:
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.merge(0xc0002cb850, 0x1, 0x1, 0x0)
    	/home/henres/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.1.1/go/pulumi/resource.go:226 +0x70
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.(*Context).RegisterResource(0xc00026e200, 0x1c439dd, 0x1d, 0x1c3ad5c, 0x13, 0x1d45040, 0xc000259900, 0x1d5d0a0, 0xc00000c5a0, 0xc0002cb850, ...)
    	/home/henres/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.1.1/go/pulumi/context.go:419 +0x1a6
    github.com/pulumi/pulumi-gcp/sdk/v3/go/gcp/container.NewCluster(0xc00026e200, 0x1c3ad5c, 0x13, 0xc000259900, 0xc0002cb850, 0x1, 0x1, 0xc0002d6270, 0x0, 0xc0002797e0)
    	/home/henres/go/pkg/mod/github.com/pulumi/pulumi-gcp/sdk/v3@v3.4.0/go/gcp/container/cluster.go:225 +0xe5
    main.main.func1(0xc00026e200, 0x1c3aeb2, 0x13)
    	/home/henres/project/pichet/gke-clustering/pulumi-poc/main.go:12 +0xb0
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.RunWithContext(0xc00026e200, 0x1c6a170, 0xc00003638f, 0xa)
    	/home/henres/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.1.1/go/pulumi/run.go:101 +0x1ff
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.RunErr(0x1c6a170, 0x0, 0x0, 0x0, 0x0, 0x0)
    	/home/henres/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.1.1/go/pulumi/run.go:82 +0x20a
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.Run(0x1c6a170, 0x0, 0x0, 0x0)
    	/home/henres/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.1.1/go/pulumi/run.go:39 +0x59
    main.main()
    	/home/henres/project/pichet/gke-clustering/pulumi-poc/main.go:9 +0x3e
    exit status 2
```

If I tried to use storage :
```golang
// main.go
package main

import (
	"github.com/pulumi/pulumi-gcp/sdk/v3/go/gcp/storage"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		_, err := storage.NewBucket(ctx, "mon-bucket-test", &storage.BucketArgs{
			Location: pulumi.String("europe-west1-b"),
		})

		if err != nil {
			return err
		}

		return nil
	})
}
```

It work normally :
```bash
$ pulumi up
Previewing update (dev):
     Type                   Name             Plan       
 +   pulumi:pulumi:Stack    pulumi-poc-dev   create     
 +   └─ gcp:storage:Bucket  mon-bucket-test  create     
 
Resources:
    + 2 to create

Do you want to perform this update? no
confirmation declined, not proceeding with the update
```

I'm not sure if it's come from my code or from a problem with the library.

Thanks for your works !

**Comment by stack72** [comment] 2020-05-13 14:18
Hi @henres 

The issue is indeed passing the `nil` as the 3rd argument to the function. We are tracking this bug https://github.com/pulumi/pulumi/issues/4549

I'm sorry you hit this bug

I will try and get this fixed in the upcoming iteration

Paul

**Comment by henres** [comment] 2020-05-14 07:31
Hi @stack72,
Thanks.
Awaiting for the fix.
It's somewhat blocking for my PoC.

Henri

**Comment by henres** [comment] 2020-05-14 12:34
For now :
```golang
		// Deploy the latest version of the stable/wordpress chart.
		_, err := container.NewCluster(ctx, "bootstrap",
			&container.ClusterArgs{
				Project:  pulumi.String("isf-kariba-sandbox"),
				Name:     pulumi.String("gke-clustering-poc"),
				Location: pulumi.String("europe-west1-b"),
			},
			pulumi.DeleteBeforeReplace(false),
		)
		if err != nil {
			return err
		}
```

**Comment by stack72** [comment] 2020-05-14 12:52
Hi @henres 

You don't actually need that 3rd parameter - the fix will be to give a useful error message :)

So the code "for now" is actually correct code :)

Paul

**Closed** 2023-03-07 17:05 UTC
Labels: kind/bug
