### ISSUE TITLE
pulumi import gcp:serviceAccount/account:Account -> wrong example code

### ISSUE THREAD

**Issue by raphaelauv** [pulumi/pulumi-gcp#687] opened 2021-11-09 21:58 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

when importing a gcp:serviceAccount/account:Account ressource 

```shell
pulumi import gcp:serviceAccount/account:Account TOTO projects/XXXXX/serviceAccounts/XXXXXXXX
```

it then print the code to add to the code 

```python
TOTO = gcp.service_account.Account("TOTO",
    account_id="XXXX",
    description="",
    disabled=False,

```

but the path is wrong it should be `serviceaccount` without the `_`

```python
TOTO = gcp.serviceaccount.Account("TOTO",
    account_id="XXX",
    description="",
    disabled=False,
```

**Comment by leezen** [comment] 2021-11-12 13:54
Thank you for the report. Closing as a dupe of #580

**Closed by leezen** 2021-11-12 13:54 UTC
Labels: kind/bug, resolution/duplicate
