### ISSUE TITLE
Unable to push to GCR using a Service Account

### ISSUE THREAD

**Issue by kevinwolfdev** [pulumi/pulumi-gcp#308] opened 2020-03-26 18:39 UTC
I'm trying to deploy a docker image to GCR from a GitHub Action using a service account with `Project > Owner` role, as recommended on the GCP Setup documentation. However, when I try to run `pulumi up`, I get the following error:

```
error: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

In my local environment, everything works fine since I use the Application Default credentials and my local docker is configured to push to GCR because I ran `gcloud auth configure-docker`.

This is the code of the service:

```ts
import * as pulumi from '@pulumi/pulumi'
import * as gcp from '@pulumi/gcp'
import * as docker from '@pulumi/docker'

import * as path from '../utils/path'
import * as constants from '../config/constants'
import * as api from '../config/api'

export const serviceName = 'app-service'

export const image = new docker.Image(`${serviceName}-image`, {
  imageName: pulumi.interpolate`gcr.io/${gcp.config.project}/${serviceName}`,
  build: {
    context: path.fromRoot(),
    dockerfile: path.fromRoot('app', 'Dockerfile'),
  },
})

export const service = new gcp.cloudrun.Service(
  serviceName,
  {
    location: constants.region,
    template: {
      spec: {
        containers: [{ image: image.imageName }],
      },
    },
  },
  { dependsOn: api.cloudRun }
)

export const iamMember = new gcp.cloudrun.IamMember(
  `${serviceName}-iam-member`,
  {
    location: constants.region,
    service: service.name,
    role: 'roles/run.invoker',
    member: 'allUsers',
  }
)
```

**Comment by leezen** [comment] 2020-03-27 04:09
Could you please provide more information on how your GHA is setup? Is it using a `GOOGLE_CREDENTIALS` env var or how is it obtaining credentials?

**Comment by kevinwolfdev** [comment] 2020-03-27 09:20
Yes, it is using a `GOOGLE_CREDENTIALS` env var with the contents of the downloaded service account key.  I created a repo for it: https://github.com/kevinwolfdev/pulumi-playground

**Comment by kevinwolfdev** [comment] 2020-03-28 20:21
@leezen any recommended solution?

**Comment by leezen** [comment] 2020-03-29 23:45
Sorry, nothing immediately comes to mind. The way you've described it looks correct (looking at your repo). I assume you've debugged to double check that the env var GOOGLE_CREDENTIALS actually contains the correct JSON contents of the key file? Otherwise, I was testing this out on my own and couldn't reproduce the issue.

**Comment by kevinwolfdev** [comment] 2020-03-30 00:50
@leezen thank you for your response. I did both testing on GitHub and on my local machine (removing the extra docker config and running `pulumi up` with `GOOGLE_CREDENTIALS=$(cat service-account.json)` but with no errors. 

Do you say you were able to run it? Is there a way you can help me do it somehow? Our company is really looking forward to start using Pulumi.

**Comment by leezen** [comment] 2020-03-30 05:47
When you say you got this to work on GitHub, I assume you mean some non-GHA mechanism? I'm curious what other way you tried?

**Comment by kevinwolfdev** [comment] 2020-03-30 05:49
So sorry, I wrote it bad. I meant: I tested it on GHA and my local machine, but **with the same** errors.

**Comment by leezen** [comment] 2020-03-30 05:54
I'm curious if you've tried a simpler Pulumi program, e.g. create a bucket with `GOOGLE_CREDENTIALS`? I'm wondering if somehow your `Project > Owner` role doesn't have the right permissions? For example, if you run `gcloud services list --available` as the service account (e.g. `gcloud auth activate-service-account --key-file=...`) do you see `containerregistry.googleapis.com` listed?

**Comment by kevinwolfdev** [comment] 2020-03-30 06:08
It is weird. I am not even being able to list my services. It says the service account doesn't have access to the project.

I created a short video: https://drive.google.com/file/d/1NLGYK2-_HqU1MgybIMRg9DRzdcL-We5U/view?usp=sharing

**Comment by leezen** [comment] 2020-03-30 16:45
Thanks for the video.  It's hard to say why that's the case... I don't know how your project or accounts are setup. One thing potentially worth checking is if the `Owner` role actually has all the permissions you expect (find this under `IAM & Admin > Roles` in the gcloud console)

**Comment by kevinwolfdev** [comment] 2020-03-30 18:06
Ok, so I just deleted my old project, created a new one, created a service account with `Project > Owner` permissions, downloaded the `json` file and activated the service account. Now I am able to see `containerregistry.googleapis.com` in my available services.

![Screenshot 2020-03-30 at 11 48 13](https://user-images.githubusercontent.com/3157426/77944667-93d5e080-727c-11ea-9bda-6fe73ff72080.png)

But again, when trying to push the container from GitHub actions, I am still receiving the permissions error, which makes me think the following:

1. Since I am building and pushing the image using `@pulumi/docker`, it is not running `gcloud auth configure-docker`.

2. According to the documentation, [there is a way to authenticate to docker using an access token](https://cloud.google.com/container-registry/docs/advanced-authentication#token), so I tried adding the `registry` configuration to the `docker.Image` and it worked, but I had to hardcode the password:

```ts
const image = new docker.Image(`${serviceName}-image`, {
  imageName: pulumi.interpolate`gcr.io/${gcp.config.project}/${serviceName}`,
  build: {
    context: path.fromRoot(),
    dockerfile: path.fromRoot('app', 'Dockerfile'),
  },
  registry: {
    server: 'https://gcr.io',
    username: 'oauth2accesstoken',
    password: 'XXXXXXXX',
  },
})

Which makes me want to ask two more questions:

1. Is there a way to programmatically get the outputs of `gcloud auth print-access-token` within the Pulumi program?
2. Can the above be abstracted into a new class of the `@pulumi/gcp` package? Maybe something like `Pulumi.registry.Image`, that is just an abstraction over the above code?

**Comment by lukehoban** [comment] 2020-03-30 21:29
> Since I am building and pushing the image using @pulumi/docker, it is not running gcloud auth configure-docker.

Yes - it does not do this - as it is just working abstractly at the `docker build`/`docker push` layer.  You could script in the call to `gcloud auth configure-docker` from your code though?  (Or run it separately to setup your CI environment?)

> Is there a way to programmatically get the outputs of gcloud auth print-access-token within the Pulumi program?

Yep - see `gcp.organizations.getClientConfig`: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/gcp/organizations/#GetClientConfigResult-accessToken.

> Can the above be abstracted into a new class of the @pulumi/gcp package? Maybe something like Pulumi.registry.Image, that is just an abstraction over the above code?

Possibly.  The AWSX package has a similar idea for AWS, and this is the sort of things that may make sense in a GCPX package.

**Comment by kevinwolfdev** [comment] 2020-03-30 21:42
> Yes - it does not do this - as it is just working abstractly at the `docker build`/`docker push` layer. You could script in the call to `gcloud auth configure-docker` from your code though? (Or run it separately to setup your CI environment?)

The problem here is that I am not installing `gcloud` at all within my CI environment, it is getting called within the Pulumi GH action.

> Yep - see `gcp.organizations.getClientConfig`: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/gcp/organizations/#GetClientConfigResult-accessToken.

Thanks! I [added a commit](https://github.com/kevinwolfdev/pulumi-playground/commit/fff10512c40e184d0115be219fde57e80558a2d9) getting the `accessToken` programmatically and [it worked](https://github.com/kevinwolfdev/pulumi-playground/runs/546875061?check_suite_focus=true) 🚀

> Possibly. The AWSX package has a similar idea for AWS, and this is the sort of things that may make sense in a GCPX package.

I think this is a nice approach, given that other developers can run into the same issue. Happy to help with a PR and then updating [this document](https://www.pulumi.com/blog/google-cloud-run-serverless-containers/).

Another question: what is the difference between the existing `gcp` package and a new `gcpx` package?

**Comment by leezen** [comment] 2020-03-30 21:59
The `gcp` and `aws` packages are meant to represent the resources themselves and in some cases, some convenience 'mix-ins' (e.g. listeners for SNS topics). A new `gcpx` and the existing `awsx` packages are meant to provide 'opinionated' best-practices ways of interacting with the cloud provider (see also https://www.pulumi.com/docs/guides/crosswalk/aws/)

**Comment by kevinwolfdev** [comment] 2020-03-31 00:36
Ok, understood. And I am happy to collaborate creating an initial draft of a `@pulumi/gcpx` package. I already did a small factory that creates a docker image, a cloud run service, and an IamMember, and exports them.

Look at the utility function: https://github.com/kevinwolfdev/pulumi-playground/blob/master/infra/src/utils/create-cloudrun-service.ts

A nice way to integrate that into a `gcpx` package can be exporting a class like `gcpx.serverless.CloudRunService` and under the hood creates those resources.

An instantiation can be something like:

```ts
const appService = new gcpx.serverless.CloudRunService('app', dockerArgs, cloudRunServiceArgs, customResourceOptions)
```

**Comment by leezen** [comment] 2020-03-31 05:18
Awesome! Thanks for sharing that

**Comment by leezen** [comment] 2020-03-31 05:19
It sounds like you've got things figured out now -- I'll close this issue, but feel free to re-open if that's not the case.

**Comment by kevinwolfdev** [comment] 2020-03-31 05:20
Thanks! But what about the `@pulumi/gcpx` package, does it make sense to create one?

**Closed by leezen** 2020-03-31 05:19 UTC

**Comment by leezen** [comment] 2020-04-09 05:08
@kevinwolfdev It'd be great if you want to take a shot at building an initial version of a helper library for GCP. Feel free to call it gcpx or whatever you'd like! I'll be more than happy to code review if you'd like or give a plug on community Slack.

**Comment by leandro-branco** [comment] 2022-12-14 04:13
Unfortunately, the repo link is broken. @kevinwolfcr could you kindly share the correct repo link or how you made it work please? Thanks!
