### ISSUE TITLE
GCP node.js provider defaults to automaticRestart=false for VMs

### ISSUE THREAD

**Issue by danderson** [pulumi/pulumi-gcp#107] opened 2019-03-07 22:29 UTC
Test driving Pulumi on GCP, I used the following config:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as gcp from "@pulumi/gcp";

const vm = new gcp.compute.Instance("pulumi-test", {
    bootDisk: {
        initializeParams: {
            image: "cos-cloud/cos-stable",
        },
    },
    deletionProtection: true,
    machineType: "g1-small",
    networkInterfaces: [{
        accessConfigs: [{}],
        network: "default",
    }],
    zone: "us-central1-a",
    name: "pulumi-test",
});
```

Upon applying this config, I end up with a GCE VM that has automatic restarts turned off. Specifically the property `scheduling.automaticRestart` is `false`.

The default for GCE is `true`, meaning that if the platform has to halt the VM for whatever reason it'll restart it. This feels like a landmine in Pulumi, where it's deviating from the platform default settings.

I believe the default should be to set `automaticRestart=true`, to match the platform's recommended default. WDYT?

**Comment by lukehoban** [comment] 2019-03-08 10:09
I was able to reproduce this.  Oddly though, the upstream Terraform Google provider does mark this `Default: true`, and deploying a similar program with Terraform does produce a `true` value for `automaticRestart`.  I also don't see any recent changes in this space in the provider.

**Comment by jen20** [comment] 2019-03-20 18:43
I believe this issue has been fixed with the work @pgavlin did on default population in the Terraform bridge recently. To reproduce, I used the exact program @danderson provided with version 0.17.1 of both the CLI and the GCP provider, but with `name` removed as a property in favour of allowing the autonamer (to prevent conflicts).

After running the program, the value of `automaticRestart` is true:

```shell
$ pulumi stack export | jq '.deployment.resources[] | select(.urn | contains("pulumi-test")) | .outputs.scheduling.automaticRestart'
true
```

This is confirmed in the GCP console:

![image](https://user-images.githubusercontent.com/548524/54710490-0ad28800-4b05-11e9-9b77-1eabfd36d3e5.png)

I'll close out this issue since it is no longer reproducible - if anyone thinks it needs further investigation, please feel free to reopen!

**Closed by jen20** 2019-03-20 18:43 UTC
