### ISSUE TITLE
Network.Get doesn't honour DependsOn

### ISSUE THREAD

**Issue by atrauzzi** [pulumi/pulumi-gcp#685] opened 2021-11-05 14:20 UTC
- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

It looks like the static `Network.Get` method doesn't honour the `DependsOn` during the early planning phase.  Pulumi ends up prematurely calling an API that I've explicitly defined as a dependency in the deployment itself.

I suspect in order to fix this, the GCP provider needs to avoid attempting to populate `.Get` resources that have a dependency on a GCP service API as they'll likely be prerequisites.

### Steps to reproduce

```csharp
        var computeService = new Service(
            "compute",
            options: new() {
                Parent = this,
            },
            args: new ServiceArgs
            {
                ServiceName = "compute.googleapis.com",
            }
        );

        var defaultNetwork = Network.Get(
            "default",
            "default",
            options: new()
            {
                Parent = this,
                DependsOn =
                {
                    computeService,
                },
            }
        );
```

Expected: Peace and order throughout the galaxy. :milky_way:
Actual: `googleapi: Error 403: Compute Engine API has not been used in project ########### before or it is disabled.`

---

The reason why I want this is because I would like to use the `"default"` network that GCP provisions for all projects.

**Comment by leezen** [comment] 2021-11-10 02:14
It appears the `Service` resource has known timing issues (see upstream: https://github.com/hashicorp/terraform-provider-google/issues/3151 and https://github.com/hashicorp/terraform-provider-google/issues/5649). It's possible the built-in sleep "isn't enough." As a workaround, I would try adding a sleep prior as part of the dependency chain.

**Comment by yellowhat** [comment] 2021-12-23 13:42
Hi, the upstream issues are closed. Are there any update on this?

**Comment by leezen** [comment] 2022-01-05 19:07
Are you still hitting this issue? I believe in the above, you actually want to have the `Get` within an `Apply` off the resource (to ensure that it's created).

**Comment by yellowhat** [comment] 2022-01-05 19:23
I have just tried the following:

```python
from pulumi import ResourceOptions
from pulumi_gcp import compute, projects

# API
api_compute = projects.Service(
    "api_compute",
    service="compute.googleapis.com",
    disable_dependent_services=True,
)

vpc = compute.Network(
    "vpc",
    name="vpc",
    auto_create_subnetworks=False,
)

vpc_subnet1 = compute.Subnetwork(
    "subnet1",
    name="subnet1",
    network=vpc.id,
    ip_cidr_range="10.0.1.0/24",
)

# Instance
vm = compute.Instance(
    "vm",
    name="vm",
    machine_type="n2d-standard-2",
    boot_disk=compute.InstanceBootDiskArgs(
        initialize_params=compute.InstanceBootDiskInitializeParamsArgs(
            image="rocky-linux-cloud/rocky-linux-8",
            type="pd-standard",
            size=20,
        ),
    ),
    network_interfaces=[
        compute.InstanceNetworkInterfaceArgs(
            subnetwork=vpc_subnet1.id,
        )
    ],
    scheduling=compute.InstanceSchedulingArgs(
        automatic_restart=False,
        preemptible=True,
    ),
    opts=ResourceOptions(depends_on=[api_compute]),
)
```

And got:

```console
$ pulumi destroy --yes
gcp:projects:Service (api_compute):
    error: deleting urn:pulumi:dev::gcp-instance::gcp:projects/service:Service::api_compute: 1 error occurred:
    	* Error when reading or editing Project Service prj/compute.googleapis.com: Error disabling service "compute.googleapis.com" for project "prj": Error waiting for api to disable: Error code 9, message: [Error in service 'compute.googleapis.com': Could not turn off service, as it still has resources in use.
```

**Comment by leezen** [comment] 2022-01-05 20:10
Aren't the network resources also dependent on the compute service being enabled?

**Comment by yellowhat** [comment] 2022-01-06 09:56
I have just retried with:

```
vpc = compute.Network(
    "vpc",
    name="vpc",
    auto_create_subnetworks=False,
    opts=ResourceOptions(depends_on=[api_compute]),
)
```

and with a new project:

```console
 Error when reading or editing Network: googleapi: Error 403: Compute Engine API has not been used in project xxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=xxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

**Comment by leezen** [comment] 2022-01-07 03:31
@yellowhat Per the upstream issues, even though they are closed, the underlying provider code doesn't actually wait for the eventual consistency and for the service enablement to fully propagate. You'll want to either poll or add additional sleep to your program code.

I'm closing this issue as I think there are two items here, both of which are resolved:
1. the original title of the issue, which is by design as invoke calls don't take `dependsOn` options
2. the issue with the resource logic itself, which relies on eventual consistency on the provider side, which can be solved by either polling or additional waiting.
3.

**Closed** 2022-01-07 03:31 UTC
Labels: kind/bug, resolution/by-design
