### ISSUE TITLE
BucketObject is replaced with an empty zip file

### ISSUE THREAD

**Issue by ateirney** [pulumi/pulumi-gcp#1372] opened 2023-11-22 19:02 UTC
### What happened?

I ran into an issue after upgrading Pulumi to the latest version. The problem occurred during a CI build: after a refresh and an update, a resource was incorrectly updated. The end result is that the BucketObject backed by a FileArchive is replaced with an empty zip file instead of what it should be.

### Example

Below is a series of steps that can be used to replicate the issue.

Start with a `Pulumi.yaml` as provided below, replacing `<bucket>` with an accessible bucket name

```
name: tmp
runtime: yaml
variables:
  aFileArchive:
    fn::fileArchive: ./directory
resources:
  aBucketObject:
    type: gcp:storage/bucketObject:BucketObject
    properties:
      bucket: <bucket>
      name: archive.zip
      source: ${aFileArchive}
```

Set up the directory to be the archive contents.

```
mkdir directory
echo "Hello World" > directory/file.txt
```

Create a new stack, and update it.

```
PULUMI_CONFIG_PASSPHRASE= pulumi stack init tmp
PULUMI_CONFIG_PASSPHRASE= pulumi update --skip-preview
```

Check that the remote object has been updated correctly

```
gsutil ls -lh gs://<bucket>/archive.zip
```

The output should look something like below.

```
     166 B  2023-11-22T18:15:37Z  gs://<bucket>/archive.zip
TOTAL: 1 objects, 166 bytes (166 B)
```

Next, remove any temporary asset files generated by the pulumi terraform bridge. This replicates the scenario I encountered as the CI starts with an emtpy /tmp directory, without this step, everything works as expected.

```
rm /tmp/pulumi-asset-*
```

Perform a refresh of the stack. This is the step that results in the /tmp/pulumi-asset-X file becoming an empty zip archive.

```
PULUMI_CONFIG_PASSPHRASE= pulumi refresh --skip-preview
```

Perform an update of the stack. This is the update the clobbers the original object

```
PULUMI_CONFIG_PASSPHRASE= pulumi update --skip-preview
```

Review the remote object, and check to see whether it has changed.

```
gsutil ls -lh gs://<bucket>/archive.zip
```

The output I get is as follows.

```
      22 B  2023-11-22T18:18:24Z  gs://<bucket>/archive.zip
TOTAL: 1 objects, 22 bytes (22 B)
```

### Output of `pulumi about`

```
CLI          
Version      3.94.2
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME  VERSION
gcp   unknown
yaml  unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in yaml

Current Stack: organization/tmp/tmp

TYPE                                   URN
pulumi:pulumi:Stack                    urn:pulumi:tmp::tmp::pulumi:pulumi:Stack::tmp-tmp
pulumi:providers:gcp                   urn:pulumi:tmp::tmp::pulumi:providers:gcp::default
gcp:storage/bucketObject:BucketObject  urn:pulumi:tmp::tmp::gcp:storage/bucketObject:BucketObject::aBucketObject


Found no pending operations associated with tmp

Backend        
Name           andrewt-ryzen
URL            file://.
User           andrewt
Organizations  
Token type     personal

No dependencies found

Pulumi locates its logs in /tmp by default
```

### Additional context

I believe the version of the gcp plugin that is being used by the yaml is the latest v7.2.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment] 2023-11-23 01:47
Hey @ateirney. Thanks for letting us know about this. I'm sorry this isn't working as expected.

> I ran into an issue after upgrading Pulumi to the latest version.

Do you remember what version this worked correctly at? Were you upgrading the provider (gcp), the Pulumi CLI, or the Pulumi SDK?

**Comment by ateirney** [comment] 2023-11-23 02:34
Hi @iwahbe. 

The version of the gcp provider I was on before I upgraded everything was 6.67.0.

After some more research, I have found that I believe the behavior change that leaves the `/tmp/pulumi-asset-X` empty zip files in place after a `pulumi preview` was introduced in version 6.67.1 of the gcp provider.

I found that if I add `version: 6.67.0` to the resource options for `aBucketObject` and then perform the clear tmp/refresh/update cycles it works as expected. Changing the version to 6.67.1 or greater seems to reproduce this issue encountered.

**Comment by iwahbe** [comment] 2023-11-27 18:53
Hi @ateirney. Thanks for that extremely clear response.

**Comment by alexgartner-bc** [comment] 2024-01-19 16:58
We are also encountering this when upgrading from `6.62.0 -> 7.5.0` with cli version `v1.101.1`

> After some more research, I have found that I believe the behavior change that leaves the /tmp/pulumi-asset-X empty zip files in place after a pulumi preview was introduced in version 6.67.1 of the gcp provider.

Thanks for the insight, I figured there was something stuck in on the filesystem but couldn't figure out where. We've added a `rm -rf /tmp/pulumi-asset*` to our deployment process as a workaround.

**Comment by yellowhat** [comment] 2024-01-22 08:42
I am having the same problem.
If I run `pulumi up --yes --refresh` an empty file is uploaded.
Insteaf if I run `pulumi preview --refresh`, `rm -rf /tmp/pulumi-asset*` and then `pulumi up --yes` it works as expected

**Comment by VenelinMartinov** [comment] 2024-03-26 17:40
This might be caused by https://github.com/pulumi/pulumi/issues/15729 similar to https://github.com/pulumi/pulumi-aws/issues/3622

**Comment by fhp** [comment] 2024-05-07 10:10
Both linked tickets are closed now, could you revisit this issue?
Locally, I can use the workaround suggested by yellowhat, but in the Github Actions CI we use the `pulumi/actions`, and I'd rather not implement that workaround there as well.

**Comment by VenelinMartinov** [comment] 2024-05-07 14:45
I believe this issue was fixed with the above. I can no longer reproduce this locally with pulumi CLI v3.115.2 and pulumi-gcp v7.21.0.

Please LMK if you are still having issues with this!

**Closed by VenelinMartinov** 2024-05-07 14:45 UTC
Labels: kind/bug, resolution/fixed, impact/regression
