### ISSUE TITLE
When getting an existing cluster, there isn't a way to pull the kubeconfig

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-gcp#97] opened 2019-02-22 23:23 UTC
In the current cluster object, we can use the `cluster` props: `certificateAuthority`, `name`, and `endpoint` to fill in the blanks in the kubeconfig file https://gist.github.com/b01eeecacccc3e284771463ed626af5e

we only do this right now in the object constructor, when we should actually have a `kubeconfig()` method on the object.

see community slack: https://pulumi-community.slack.com/archives/C84L4E3N1/p1550871454193500?thread_ts=1550862777.160400&cid=C84L4E3N1

related: https://github.com/pulumi/pulumi-aws/issues/478

**Comment by NinoFloris** [comment] 2019-08-12 18:01
Is there some workaround besides manually templating the kubeconfig?

**Comment by lukehoban** [comment] 2019-08-12 18:18
For now - you need to copy the boilerplate from one of the examples - like https://github.com/pulumi/examples/blob/master/gcp-ts-gke/cluster.ts#L27.

This issue is tracking putting that boilerplate behind a named function in the `@pulumi/gcp` package, but should not technically be a blocker for any scenarios.

**Comment by NinoFloris** [comment] 2019-08-12 18:20
Thanks so much for the fast response!

**Comment by mikhailshilkov** [comment] 2023-07-28 12:19
Closing as a dupe of #1064

**Closed by mikhailshilkov** 2023-07-28 12:19 UTC
Labels: kind/enhancement, resolution/duplicate
