### ISSUE TITLE
Missing required argument: The argument "template.0.spec.0.containers.0.image"

### ISSUE THREAD

**Issue by maxmoeschinger** [pulumi/pulumi-gcp#827] opened 2022-06-10 08:28 UTC
### What happened?

I am trying to setup a `gcp.cloudrun.Service` with the following `ignoreChanges`:
```js
{
    ignoreChanges: ["template.spec.containers[0].image"],
},
```

When I try to update the cloudrun resource through pulumi and run `pulumi up` I get the following error:
```
Diagnostics:
  gcp:cloudrun:Service (bv-dashboard):
    error: gcp:cloudrun/service:Service resource 'bv-dashboard' has a problem: Missing required argument: The argument "template.0.spec.0.containers.0.image" is required, but no definition was found.. Examine values at 'Service.Template.Spec[0].Containers[0].WorkingDir'.

```

### Steps to reproduce

1. Create a `gcp.cloudrun.Service` with the following ignore changes: `["template.spec.containers[0].image"]`
2. Update the `gcp.cloudrun.Service` and run `pulumi up`
3. Pulumi will fail with the error described above

### Expected Behavior

I expect pulumi to actually ignore image changes so that I can have CD setup without having a diff every time i run `pulumi up`. 

### Actual Behavior

I got this error:
```
Diagnostics:
  gcp:cloudrun:Service (bv-dashboard):
    error: gcp:cloudrun/service:Service resource 'bv-dashboard' has a problem: Missing required argument: The argument "template.0.spec.0.containers.0.image" is required, but no definition was found.. Examine values at 'Service.Template.Spec[0].Containers[0].WorkingDir'.

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkisk** [comment] 2022-06-10 20:27
I believe the property needs to be designated in the code, and then again in the ignoreChanges section, if I'm understanding the issue correctly.  Here are the docs on ignoreChanges: https://www.pulumi.com/docs/intro/concepts/resources/options/ignorechanges/

**Comment by maxmoeschinger** [comment] 2022-06-11 06:22
Yes, I have also set the image name. It can create the resource but updating doesn't work.

**Comment by maxmoeschinger** [comment] 2022-06-14 08:40
Here is a sample:

```js
new gcp.cloudrun.Service(
    "my-service-name",
    {
        name: "my-service-name",
        location: "europe-west1",
        autogenerateRevisionName: true,
        template: {
            spec: {
                containers: [
                    {
                        image: "gcr.io/cloudrun/placeholder",
                    },
                ],
            },
        },
        traffics: [
            {
                latestRevision: true,
                percent: 100,
            },
        ],
    },
    {
        ignoreChanges: ["template.spec.containers[0].image"],
    },
)
```

**Comment by Frassle** [comment] 2022-06-15 08:08
I think there's a provider issue here that it's giving back a very strange error message, but I wonder if you've also misunderstood what ignoreChanges does? It looks like your after a feature like https://github.com/pulumi/pulumi/issues/8953 where if a diff happens the UI doesn't show it. IgnoreChanges does not do that, it just ignores any new value passed and uses the last seen value instead.

**Comment by maxmoeschinger** [comment] 2022-06-17 05:40
No, I just want it to use the old value. I have CD setup for this service so I don't want pulumi updating the image.

**Comment by Frassle** [comment] 2022-06-17 08:25
Thanks for confirming that.

**Comment by VladAmos** [comment] 2022-09-12 00:52
Any update on this? There is a very real functional need to fix this in that in a production environment you don't want to accidentally rollback, or forward if using the "latest" tag, a service because you rolled some other unrelated change.

**Comment by mikhailshilkov** [comment] 2023-10-26 18:35
I'm trying to repro it today with the latest version of everything. Took this program:

```
new gcp.cloudrun.Service(
    "my-service-name",
    {
        name: "my-service-name",
        location: "europe-west1",
        autogenerateRevisionName: true,
        template: {
            spec: {
                containers: [
                    {
                        image: "gcr.io/cloudrun/placeholder",
                    },
                ],
            },
        },
        traffics: [
            {
                latestRevision: true,
                percent: 100,
            },
        ],
    },
    {
        ignoreChanges: ["template.spec.containers[0].image"],
    },
)
```

1. Ran `pulumi up` to deploy it.
2. Changed one value to `latestRevision: false`.
3. Ran `pulumi up` to deploy it again.

Both deployments succeeded.

Since the issue is more than a year old, I'll assume it's fixed and will close it. Please let me know if my repro is incomplete.

**Closed by mikhailshilkov** 2023-10-26 18:35 UTC
Labels: kind/bug, resolution/fixed
