### ISSUE TITLE
Change a compute.Subnetwork ip_cidr_range triggers a replacement

### ISSUE THREAD

**Issue by jcalderin** [pulumi/pulumi-gcp#987] opened 2023-02-09 05:02 UTC
### What happened?

When changing a subnetwork ip_cicd_range the subnetwork gets replaced

### Expected Behavior

When changing a subnetwork ip_cicd_range the subnetwork gets modified without replacement. This is the behaviours on the gcp console AND what says in the documentation https://www.pulumi.com/registry/packages/gcp/api-docs/compute/subnetwork/#ip_cidr_range_python

### Steps to reproduce

Sample code

```
"""A Google Cloud Python Pulumi program"""

import pulumi
import pulumi_gcp as gcp

import pulumi_neara.gcp.services as neara_gcp_services

gcp_config = pulumi.Config("gcp")


provider = gcp.Provider(
    "gcp",
    project=gcp_config.get("project"),
    region=gcp_config.get("region"),
)

service = neara_gcp_services.enable_service("compute", opts=pulumi.ResourceOptions(provider=provider))

vpc = gcp.compute.Network(
    resource_name="jon-test",
    auto_create_subnetworks=False,
    delete_default_routes_on_create=False,
    routing_mode="REGIONAL",
    opts=pulumi.ResourceOptions(provider=provider, depends_on=service)
)

private_subnet = gcp.compute.Subnetwork(
    resource_name="private-subnet",
    ip_cidr_range="10.102.0.0/24",
    region="us-west1",
    network=vpc.id,
    private_ip_google_access=True,
    purpose="PRIVATE",
    opts=pulumi.ResourceOptions(provider=provider, depends_on=service)
)
```

output when modified ip_cidr_range
```
pulumi up
Previewing update (jon-test-1):
     Type                       Name                   Plan        Info
     pulumi:pulumi:Stack        jon-test-1-jon-test-1              
 +-  └─ gcp:compute:Subnetwork  private-subnet         replace     [diff: ~ipCidrRange]


Resources:
    +-1 to replace
    4 unchanged

Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:jon-test-1::jon-test-1::pulumi:pulumi:Stack::jon-test-1-jon-test-1]
    ++gcp:compute/subnetwork:Subnetwork: (create-replacement)
        [id=projects/sandbox-363900/regions/us-west1/subnetworks/private-subnet-991957f]
        [urn=urn:pulumi:jon-test-1::jon-test-1::gcp:compute/subnetwork:Subnetwork::private-subnet]
        [provider=urn:pulumi:jon-test-1::jon-test-1::pulumi:providers:gcp::gcp::53673d68-031d-4810-95f5-62a2ceadcfa3]
      ~ ipCidrRange: "10.101.0.0/24" => "10.102.0.0/24"
    +-gcp:compute/subnetwork:Subnetwork: (replace)
        [id=projects/sandbox-363900/regions/us-west1/subnetworks/private-subnet-991957f]
        [urn=urn:pulumi:jon-test-1::jon-test-1::gcp:compute/subnetwork:Subnetwork::private-subnet]
        [provider=urn:pulumi:jon-test-1::jon-test-1::pulumi:providers:gcp::gcp::53673d68-031d-4810-95f5-62a2ceadcfa3]
      ~ ipCidrRange: "10.101.0.0/24" => "10.102.0.0/24"
    --gcp:compute/subnetwork:Subnetwork: (delete-replaced)
        [id=projects/sandbox-363900/regions/us-west1/subnetworks/private-subnet-991957f]
        [urn=urn:pulumi:jon-test-1::jon-test-1::gcp:compute/subnetwork:Subnetwork::private-subnet]
        [provider=urn:pulumi:jon-test-1::jon-test-1::pulumi:providers:gcp::gcp::53673d68-031d-4810-95f5-62a2ceadcfa3]
```

### Output of `pulumi about`

pulumi about
CLI          
Version      3.54.0
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.27.0
gcp         6.43.0
kubernetes  3.22.1
neara       0.1.0
python      unknown
random      4.8.2

Host     
OS       darwin
Version  13.1
Arch     arm64

This project is written in python: executable='/Users/cholas/work/infra/plp-infrastructure/pulumi/venv/bin/python3' version='3.10.9
'

Current Stack: jon-test-1

TYPE                               URN
pulumi:pulumi:Stack                urn:pulumi:jon-test-1::jon-test-1::pulumi:pulumi:Stack::jon-test-1-jon-test-1
pulumi:providers:gcp               urn:pulumi:jon-test-1::jon-test-1::pulumi:providers:gcp::gcp
gcp:projects/service:Service       urn:pulumi:jon-test-1::jon-test-1::gcp:projects/service:Service::compute
gcp:compute/network:Network        urn:pulumi:jon-test-1::jon-test-1::gcp:compute/network:Network::jon-test
gcp:compute/subnetwork:Subnetwork  urn:pulumi:jon-test-1::jon-test-1::gcp:compute/subnetwork:Subnetwork::private-subnet

Found no pending operations associated with jon-test-1

Backend        
Name           CholasLappy
URL            s3://com-neara-bacek-test/pulumi/
User           cholas
Organizations  

Dependencies:
NAME              VERSION
Neara-pulumi-lib  0.1.0
pip               23.0.0
pulumi-neara      0.1.0
setuptools        65.5.0
wheel             0.37.1

Pulumi locates its logs in /var/folders/wq/j5hyjh_s25q0bvtvpvds99fm0000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by squaremo** [comment] 2023-02-13 11:02
Thanks for logging this issue ✋
What I see is this: the Pulumi documentation at https://www.pulumi.com/registry/packages/gcp/api-docs/compute/subnetwork/#ip_cidr_range_python does _not_ have the "changes trigger replacement" symbol; but, it does say this in the description:

> Provide this property when you create the subnetwork.

This wording is also used in the field `description`, and there's similar language for `name`, both of which do trigger a replacement. This leads me to suspect that **changing `ip_range_cidr` will trigger a replacement, and the documentation has it wrong**. So far as I can see, the Google Compute docs don't mention _changing_ the IPv4 subnet CIDR, other than to expand it -- https://cloud.google.com/vpc/docs/create-modify-vpc-networks#expand-subnet, and corroborated by https://cloud.google.com/compute/docs/reference/rest/v1/subnetworks/patch#request-body, which says

> This field is set at resource creation time. [...] The range can be expanded after creation using expandIpCidrRange.

So, I think we need to verify what the upstream code actually does, and investigate whether the field should have a "chnage triggers a replacement" symbol -- and if it should, why it doesn't!

**Comment by jcalderin** [comment] 2023-02-13 22:23
I believe you are right and the problem is the documentation. I changed it in the console but did an expansion, I didn't try a shrinkage and therefore didn't trigger any error. I tried again today in the console and you can only expand when you click in "edit". The GCP console is not the most intuitive either :)

**Comment by mikhailshilkov** [comment] 2023-06-20 18:10
Looking at the source upstream, this property has a conditional replace on change behavior, see here:

https://github.com/hashicorp/terraform-provider-google/blob/8561fcad045fc9bc47690da7409aa193b5455836/google/services/compute/resource_compute_subnetwork.go#L75

and here:

https://github.com/hashicorp/terraform-provider-google/blob/8561fcad045fc9bc47690da7409aa193b5455836/google/services/compute/resource_compute_subnetwork.go#L38

Since it's not a blank ForceNew, we don't show the sign in the docs.

I'll go ahead and close the issue as by design. Let me know if you have any follow-up asks. Thank you!

**Closed by mikhailshilkov** 2023-06-20 18:10 UTC
Labels: kind/bug, resolution/by-design, docs/autogenerated, area/api-docs
