### ISSUE TITLE
the example code has a bug "service_account" it should be "serviceaccount"

### ISSUE THREAD

**Issue by Jaafar-Nasrallah** [pulumi/pulumi-gcp#1128] opened 2023-07-11 03:34 UTC
File: [themes/default/content/registry/packages/gcp/api-docs/serviceAccount/account/_index.md](https://www.pulumi.com/registry/packages/gcp/api-docs/serviceaccount/account/)

**Comment by thomas11** [comment] 2023-07-21 06:54
Hi @Jaafar-Nasrallah, thank you for reporting this. I'm not sure I see what you mean on the page you linked, though. Could you describe where exactly the issue is or provide a screenshot?

**Comment by Jaafar-Nasrallah** [comment] 2023-07-21 07:36
Hi @thomas11, I'm pretty sure I am not crazy. but it seems to be fixed? 
![image](https://github.com/pulumi/pulumi-gcp/assets/15153910/677a5189-b8d5-405a-835b-01da42c8bc7e)
the "name" of the account was 'service_account' which would have caused an error. Seems to be fixed.

**Comment by Jaafar-Nasrallah** [comment] 2023-07-27 12:51
@thomas11 Sorry. I closed the issue when I shouldn't have. The last comment explains the issue 🙏

**Comment by bueti** [comment] 2023-09-19 04:45
the same happens with Go. the package is named `serviceAccount` instead of `serviceaccount` (notice the capitalized a).
The example code is wrong, and the generated code when importing a service account is wrong as well.


```go
package main

import (
	"github.com/pulumi/pulumi-gcp/sdk/v6/go/gcp/serviceAccount" // <--- should be serviceaccount
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		_, err := serviceAccount.NewAccount(ctx, "serviceAccount", &serviceAccount.AccountArgs{ 
			//^^^^^^^^^^^^^^ should be "serviceaccount"         ^^^^^^^^^^^^^^ same here
			AccountId:   pulumi.String("service-account-id"),
			DisplayName: pulumi.String("Service Account"),
		})
		if err != nil {
			return err
		}
		return nil
	})
}
```
snippet from https://www.pulumi.com/registry/packages/gcp/api-docs/serviceaccount/account/#example-usage

**Comment by mnlumi** [comment] 2023-10-26 20:17
Duplicate of https://github.com/pulumi/pulumi-gcp/issues/722

**Closed** 2023-10-26 20:17 UTC
Labels: kind/bug, resolution/duplicate, area/api-docs
