### ISSUE TITLE
pulumi up fails second time when using firestore Index

### ISSUE THREAD

**Issue by manast** [pulumi/pulumi-gcp#430] opened 2020-09-02 16:58 UTC
A index for firestore can easily be created by using:
```
    const backupIndex = new gcp.firestore.Index(
      "index",
      {
        collection: "mycollection",
        fields: [
          {
            fieldPath: "onefield",
            order: "ASCENDING",
          },
          {
            fieldPath: "anotherfield",
            order: "DESCENDING",
          },
        ],
      },
      {
        parent: this,
      }
    );
``` 

creates the index the first time ```pulumi up``` is executed. The second time however, even though no changes have been performed, a replace is scheduled for changing the fields:

```
 gcp:firestore:Index                                  index                replace     [diff: ~fields]
```
Furthermore this fails:
```
gcp:firestore:Index (backup):
    error: Error creating Index: googleapi: Error 409: index already exists
```

Ok, so lets try changing the name of the index:

```
+  gcp:firestore:Index                                  newIndex           create
- gcp:firestore:Index                                  index                delete
```
It also fails:
```
error: Error creating Index: googleapi: Error 409: index already exists
```

**Comment by leezen** [comment] 2020-09-02 19:47
This is tracked in https://github.com/pulumi/pulumi/issues/2625

Regarding the diff you saw, could you please provide the detailed diff? I wonder if it's an ordering thing with the API returning a different order, in which case, could this be solved by ordering the fields in the same order?

**Comment by manast** [comment] 2020-09-02 21:41
I will try to reproduce again and provide the diff. Regarding this issue and #2625 seems like a serious one, what is the workaround when this happens?

**Comment by manast** [comment] 2020-09-02 22:09
Ok, it is actually trivial to reproduce, just create a stack with a index as above and run it two times, you will get the following diff:
```
pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::taskforce-infra::pulumi:pulumi:Stack::taskforce-infra-dev]
        ++gcp:firestore/index:Index: (create-replacement)
            [id=projects/taskforce-pulumi-test/databases/(default)/collectionGroups/backups/indexes/CICAgJiUpoMK]
            [urn=urn:pulumi:dev::taskforce-infra::taskforce:region$gcp:firestore/index:Index::index]
            [provider=urn:pulumi:dev::taskforce-infra::pulumi:providers:gcp::default_3_21_0::6306b95b-1e56-41dc-82ef-f6e84c518f2f]
          ~ fields: [
              - [2]: {
                      - fieldPath  : "__name__"
                      - order      : "DESCENDING"
                    }
            ]
        +-gcp:firestore/index:Index: (replace)
            [id=projects/taskforce-pulumi-test/databases/(default)/collectionGroups/backups/indexes/CICAgJiUpoMK]
            [urn=urn:pulumi:dev::taskforce-infra::taskforce:region$gcp:firestore/index:Index::index]
            [provider=urn:pulumi:dev::taskforce-infra::pulumi:providers:gcp::default_3_21_0::6306b95b-1e56-41dc-82ef-f6e84c518f2f]
          ~ fields: [
              - [2]: {
                      - fieldPath  : "__name__"
                      - order      : "DESCENDING"
                    }
            ]
        --gcp:firestore/index:Index: (delete-replaced)
            [id=projects/taskforce-pulumi-test/databases/(default)/collectionGroups/backups/indexes/CICAgJiUpoMK]
            [urn=urn:pulumi:dev::taskforce-infra::taskforce:region$gcp:firestore/index:Index::index]
            [provider=urn:pulumi:dev::taskforce-infra::pulumi:providers:gcp::default_3_21_0::6306b95b-1e56-41dc-82ef-f6e84c518f2f]
```

**Comment by manast** [comment] 2020-09-03 16:21
Thats a separate issue, the main problem here is that it detects a diff when in fact no changes have been performed, which currently makes the use of Index impossible.

**Comment by manast** [comment] 2020-09-03 16:22
regarding deleteBeforeReplace, I agree on what you say.

**Comment by mnlumi** [comment] 2023-07-26 20:19
Need to retest and see if this is still an issue.

**Comment by mikhailshilkov** [comment] 2023-10-30 10:26
I tried reproducing the issue today. I ran the program above but I am not getting any diffs on subsequent `pulumi up`. I'll assume this has been closed in those 3 years since the original issue.

**Closed by mikhailshilkov** 2023-10-30 10:26 UTC
Labels: kind/bug, resolution/fixed
