### ISSUE TITLE
Gettin' whalloped by arbitrary GCP Secret replacements

### ISSUE THREAD

**Issue by atrauzzi** [pulumi/pulumi-gcp#1612] opened 2024-01-31 02:46 UTC
### What happened?

Ran Pulumi for the first time in a bit.  Got mostly some workable updates, but ended up getting hit by this once for every secret in my secret manager:

```
++gcp:secretmanager/secret:Secret: (create-replacement)
        [id=SOMESECRET]
        [urn=urn:pulumi:SOMESECRET]
        [provider: urn:pulumi:whatever::whatever::pulumi:providers:gcp::default_6_67_0::GUID => urn:pulumi:whatever::whatever::pulumi:providers:gcp::default_7_7_0::GUID]
        replication: {
            automatic : true
        }
        secretId   : "SOMESECRET"
    +-gcp:secretmanager/secret:Secret: (replace)
        [id=SOMESECRET]
        [urn=urn:pulumi:whatever::whatever::gcp:secretmanager/secret:Secret::SOMESECRET]
        [provider: urn:pulumi:whatever::whatever::pulumi:providers:gcp::default_6_67_0::GUID => urn:pulumi:whatever::whatever::pulumi:providers:gcp::default_7_7_0::GUID]
        replication: {
            automatic : true
        }
        secretId   : "SOMESECRET"
```

I also had to set up this boilerplate for my secret instances, or else pulumi would crash with some exception saying that it was missing:

```csharp
                var secret = new Secret(secretId, new()
                {
                    SecretId = secretId,
                    Replication = new SecretReplicationArgs
                    {
                        Auto = new SecretReplicationAutoArgs(),
                    },
                });
```

### Output of `pulumi about`

```
❯ pulumi about
CLI          
Version      3.103.1
Go Version   go1.21.5
Go Compiler  gc

Host     
OS       fedora
Version  39
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment] 2024-01-31 10:48
Hi @atrauzzi. I'm sorry you're seeing this.

I believe that this is a duplicate of https://github.com/pulumi/pulumi-gcp/issues/1488.

**Closed by iwahbe** 2024-01-31 10:48 UTC
Labels: kind/bug, resolution/duplicate

**Comment by iwahbe** [comment] 2024-02-01 09:52
@atrauzzi We are working on this problem now. In the mean time, I would recommend pinning the provider to v6.67.0. The issue is caused by upgrading between major versions of gcp.

**Comment by iwahbe** [comment] 2024-02-01 15:53
If you were feeling particularly ambitious, you could edit the version string in your state file (`pulumi stack export | edit | pulumi stack import`). I'm not 100% sure that it will work, but I think there is a >70% chance.
