### ISSUE TITLE
GCP eventarc path filter doesn't work

### ISSUE THREAD

**Issue by petercheng00** [pulumi/pulumi-gcp#831] opened 2022-06-14 22:56 UTC
### What happened?

I'd like an eventarc trigger based on a specific file pattern in google cloud storage. This is done via --event-filters-path-pattern in google cloud documentation.

See the slack thread here: https://pulumi-community.slack.com/archives/CRFUR2DGB/p1655238434066829

### Steps to reproduce

Here's what I'm using (the resourceName section is copied directly from [this google sample](https://github.com/GoogleCloudPlatform/declarative-resource-client-library/blob/ea137f607a2d00eda762cc9565bce1f3bd9c3dfd/services/google/eventarc/samples/basic.trigger.json#L29-L31) as a test :

            matchingCriterias: [
                {
                    attribute: "type",
                    value: "google.cloud.storage.object.v1.finalized",
                },
                {
                    attribute: "bucket",
                    value: bucketName,
                },
                {
                    attribute: "resourceName",
                    value: "/projects/_/buckets/bucket-1/objects/*",
                    operator: "match-path-pattern"
                }
            ],

### Expected Behavior

Trigger gets created

### Actual Behavior

error: 1 error occurred:
    	* Error updating Trigger: googleapi: Error 400: The request was invalid: The request was invalid: invalid attribute "resourceName" for trigger.event_filters

### Versions used

CLI          
Version      3.34.1
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME    VERSION
docker  3.2.0
gcp     6.24.0
nodejs  unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

Dependencies:
NAME            VERSION
@types/node     14.18.18
@pulumi/docker  3.2.0
@pulumi/gcp     6.24.0
@pulumi/pulumi  3.33.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment] 2022-06-16 10:24
Hi @petercheng00 

Thanks for opening the issue here - please can you provide the code that will help us try and recreate the issue. That will help be able to isolate the problem here

Paul

**Comment by petercheng00** [comment] 2022-06-27 01:31
```
trigger = new gcp.eventarc.Trigger("trigger", {
    location: serviceLocation,
    serviceAccount: serviceAccount,
    matchingCriterias: [
        {
            attribute: "type",
            value: "google.cloud.storage.object.v1.finalized",
        },
        {
            attribute: "bucket",
            value: bucketName,
        },
        {
            attribute: "resourceName",
            value: "/projects/_/buckets/bucket-1/objects/*",
            operator: "match-path-pattern"
        }
    ],
    destination: {
        cloudRunService: {
            service: serviceName,
            region: serviceLocation,
        },
    },
});
```

**Comment by linco95** [comment] 2023-02-27 15:49
@petercheng00 The trigger you linked is using the `google.cloud.audit.log.v1.written` event, which contains the `resourceName` attribute, and hence works in their example. While the trigger you've shown here is using `google.cloud.storage.object.v1.finalized` and that only contains `bucket` and `type` attribute.

**Comment by mikhailshilkov** [comment] 2023-10-27 12:48
Given the previous comment, I'll close the issue as by design. Let me know if you think it's wrong.

**Closed by mikhailshilkov** 2023-10-27 12:48 UTC
Labels: kind/bug, resolution/by-design
