### ISSUE TITLE
Service account resource module name wrong in python

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-gcp#668] opened 2021-10-15 16:11 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

See python example [here](https://www.pulumi.com/docs/reference/pkg/gcp/serviceaccount/account/)

Code looks like:

```python
import pulumi
import pulumi_gcp as gcp

service_account = gcp.service_account.Account("serviceAccount",
    account_id="service-account-id",
    display_name="Service Account")
```

but should be 

```python
import pulumi
import pulumi_gcp as gcp

service_account = gcp.serviceaccount.Account("serviceAccount",
    account_id="service-account-id",
    display_name="Service Account")
```

(`service_account` to `serviceaccount`)

**Comment by remintz** [comment] 2022-08-17 18:47
This also happens with the code generated on a `pulumi import`. The code is generated with `gcp.service_account.Account` instead of `gcp.serviceaccount.Account`.

**Comment by mnlumi** [comment] 2023-10-26 20:18
Duplicate of https://github.com/pulumi/pulumi-gcp/issues/722

**Closed by mnlumi** 2023-10-26 20:18 UTC
Labels: area/docs, kind/bug, resolution/duplicate
