### ISSUE TITLE
Fix service account namespace

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-gcp#811] opened 2022-05-14 20:05 UTC
We have multiple reports of the service account namespace rendering incorrectly, which also causes 404's in the registry:

* https://github.com/pulumi/pulumi-gcp/issues/722
* https://github.com/pulumi/registry/issues/758
* https://github.com/pulumi/pulumi-gcp/issues/668
* https://github.com/pulumi/pulumi-gcp/issues/580

Need to discuss internally, since this is technically a breaking change. The module name looks correct, but we need to look into what removing [this block of code](https://github.com/pulumi/pulumi-gcp/blob/master/provider/resources.go#L115-L119) would do and figure out a release strategy, since this is technically a breaking change (although I'm not sure of how many users it would affect).

**Comment by mnlumi** [comment] 2023-10-26 20:22
Duplicate of https://github.com/pulumi/pulumi-gcp/issues/722

**Closed by mnlumi** 2023-10-26 20:22 UTC
Labels: area/docs, kind/bug, resolution/duplicate
