### ISSUE TITLE
Python import of `service_account` fails / documenation wrong

### ISSUE THREAD

**Issue by v0lk3r** [pulumi/pulumi-gcp#580] opened 2021-05-19 09:01 UTC
I am trying to create a Service Account on GCP with the pulumi python module according to the documentation. This fails with an import error

Following the example usage described in the documentation https://www.pulumi.com/docs/reference/pkg/gcp/serviceaccount/account/ 

```
import pulumi
import pulumi_gcp as gcp

service_account = gcp.service_account.Account("serviceAccount",
    account_id="service-account-id",
    display_name="Service Account")
```
results in this error:

```
  File "./__main__.py", line 24, in <module>
    service_account = gcp.service_account.Account(
AttributeError: module 'pulumi_gcp' has no attribute 'service_account'
```

I would expect this to properly create a service account

Versions: `pulumi-gcp==5.3.0`, pulumi version v3.2.1

Looking at the code https://github.com/pulumi/pulumi-gcp/blob/master/sdk/python/pulumi_gcp/__init__.py#L75 shows that underscores seem to be removed.

So the above code works when removing the underscore in the module as well. I am assuming this will fail for other modules as well.

I would propose to either fix the documentation or change the code to not remove the underscores

**Comment by Bharathkumarraju** [comment] 2021-06-28 12:28
@v0lk3r any fix for this? i get the same error :(

```
"""A Google Cloud Python Pulumi program"""
import pulumi
import pulumi_gcp as gcp

service_account = gcp.service_account.Account("serviceAccount",
    account_id="pulumiautomation",
    display_name="pulumi-automation")
```

and the `pulumi preview` throws the error like below.

```
bharathdasaraju@MacBook-Pro pulumi-test $ pulumi preview
Previewing update (bksa)

View Live: https://app.pulumi.com/Bharathkumarraju/bharathtests/bksa/previews/e7e92e87-63ab-413a-8157-acc57080fee5

     Type                 Name               Plan       Info
 +   pulumi:pulumi:Stack  bharathtests-bksa  create     3 errors

Diagnostics:
  pulumi:pulumi:Stack (bharathtests-bksa):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 92, in <module>
        loop.run_until_complete(coro)
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
        return future.result()
      File "/Users/bharathdasaraju/git/pulumi-test/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 110, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/bharathdasaraju/git/pulumi-test/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 43, in run_pulumi_func
        func()
      File "/Users/bharathdasaraju/git/pulumi-test/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 110, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/bharathdasaraju/git/pulumi-test/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 133, in __init__
        func()
      File "/usr/local/bin/pulumi-language-python-exec", line 91, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 285, in run_path
        return _run_code(code, mod_globals, init_globals,
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/Users/bharathdasaraju/git/pulumi-test/./__main__.py", line 5, in <module>
        service_account = gcp.service_account.Account("serviceAccount",
    AttributeError: module 'pulumi_gcp' has no attribute 'service_account'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
bharathdasaraju@MacBook-Pro pulumi-test $
```

**Comment by Bharathkumarraju** [comment] 2021-06-28 12:31
@v0lk3r  Thank you!!! 👍  it worked if i change like below.

```
bharathdasaraju@MacBook-Pro pulumi-test $ cat __main__.py
"""A Google Cloud Python Pulumi program"""
import pulumi
import pulumi_gcp as gcp

service_account = gcp.serviceaccount.Account("serviceAccount",
    account_id="pulumiautomation",
    display_name="pulumi-automation")
bharathdasaraju@MacBook-Pro pulumi-test $
```

```
bharathdasaraju@MacBook-Pro pulumi-test $ pulumi preview
Previewing update (bksa)

View Live: https://app.pulumi.com/Bharathkumarraju/bharathtests/bksa/previews/e35535fc-6645-4068-935e-1c772f76e163

     Type                           Name               Plan
 +   pulumi:pulumi:Stack            bharathtests-bksa  create
 +   └─ gcp:serviceAccount:Account  serviceAccount     create

Resources:
    + 2 to create

bharathdasaraju@MacBook-Pro pulumi-test $
```

**Comment by Bharathkumarraju** [comment] 2021-06-28 12:33
`pulumi up` worked as well.

```

**Comment by jdoss** [comment] 2022-03-23 22:31
Can I make a PR for this fix? If so, where? I ran into this documentation snafu today.

**Comment by noahdatasherpas** [comment] 2022-10-11 02:00
This still isn't fixed... it's been a year and a half since this issue was opened. All other threads point back to this one.

What would it take to make the change to the documentation? I'd be happy to make the change if someone can point me in the right direction. Seems like updating the documentation example should be a quick one liner?

**Comment by edeustua** [comment] 2023-06-18 22:48
I can confirm this issue still exists.

**Comment by edeustua** [comment] 2023-06-18 22:49
This is still an issue.

**Comment by mnlumi** [comment] 2023-10-26 20:21
Duplicate of https://github.com/pulumi/pulumi-gcp/issues/722

**Closed by mnlumi** 2023-10-26 20:21 UTC
Labels: kind/bug, resolution/duplicate
