### ISSUE TITLE
[Docs][Python] Incorrect name for service account module

### ISSUE THREAD

**Issue by scottslowe** [pulumi/pulumi-gcp#919] opened 2022-10-04 16:43 UTC
### What happened?

I went to the API documentation to get the details necessary to use Python to create a GCP Service Account (https://www.pulumi.com/registry/packages/gcp/api-docs/serviceaccount/account/). The code example at the top references `gcp.service_account.Account`, but this produces an error. The correct reference should be `gcp.serviceaccount.Account`.

### Steps to reproduce

1. Create a new Python program using the GCP Classic provider.
2. Try to create a GCP service account using the existing documentation.
3. Upon `pulumi preview`, you'll see an error indicating that `service_account` is an unknown module name.
4. Change `gcp.service_account.Account` to `gcp.serviceaccount.Account` and repeat step 3. The error will be gone.

### Expected Behavior

I expected the documentation to properly reference the name of the module.

### Actual Behavior

The name of the module was incorrect in the documentation.

### Output of `pulumi about`

N/A

### Additional context

No

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mnlumi** [comment] 2023-10-26 20:18
Duplicate of https://github.com/pulumi/pulumi-gcp/issues/722

**Closed by mnlumi** 2023-10-26 20:18 UTC
Labels: area/docs, kind/bug, resolution/duplicate
