### ISSUE TITLE
Adding 'website' configuration to GCS bucket causes panic

### ISSUE THREAD

**Issue by casey-robertson** [pulumi/pulumi-gcp#146] opened 2019-05-14 23:21 UTC
GCP project currently hosts 3 buckets set with FQDNs and the 'allUsers' permission making them public.  Request from software team that 404 responses are routed to 'index.html'.  

Implement the following change in my Pulumi code (website section added to bucket creation):

```
const bucket = new gcp.storage.Bucket(bucketName, {
            name: bucketName,
            project,
            cors: corsPolicy,
            websites: [
                {
                    notFoundPage,
                    mainPageSuffix
                }
            ]
        });
```

Pulumi preview shows the addition of the websites.  `pulumi up -y` however results in the below:

```
Diagnostics:
  gcp:storage:Bucket (caseypayments.mindbody.io):
    error: Plan apply failed: all SubConns are in TransientFailure, latest connection error: <nil>

  gcp:compute:ProjectMetadata (default-metadata):
    error: Plan apply failed: transport is closing

  gcp:dns:RecordSet (origin-signin.casey.arcusplatform.io.):
    error: all SubConns are in TransientFailure, latest connection error: <nil>

  gcp:storage:Bucket (signin.casey.arcusplatform.io):
    error: Plan apply failed: transport is closing

  pulumi:pulumi:Stack (viserion-casey-robertson):
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x24ee67f]
    goroutine 153 [running]:
    github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta.resourceStorageBucketUpdate(0xc000157960, 0x2a7a6c0, 0xc000284820, 0x24, 0x4555700)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta/resource_storage_bucket.go:395 +0xfff
    github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc000444800, 0xc000a4d450, 0xc0006dcd20, 0x2a7a6c0, 0xc000284820, 0x1, 0xc00084d688, 0xc00084d6a0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:292 +0x264
    github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc000445300, 0xc00084d868, 0xc000a4d450, 0xc0006dcd20, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:285 +0x18f
    github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Update(0xc0002e2b40, 0x320b5a0, 0xc0006b4e70, 0xc000a4d400, 0xc0002e2b40, 0x2a69c01, 0xc000612200)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:721 +0x70c
    github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Update_Handler.func1(0x320b5a0, 0xc0006b4e70, 0x2d2b660, 0xc000a4d400, 0x2d6aa60, 0x4553fa0, 0x320b5a0, 0xc0006b4e70)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1367 +0x86
    github.com/pulumi/pulumi-gcp/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x320b5a0, 0xc0006b4300, 0x2d2b660, 0xc000a4d400, 0xc000793e60, 0xc000793e80, 0x0, 0x0, 0x31c2e60, 0xc00025be20)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x360
    github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Update_Handler(0x2db54e0, 0xc0002e2b40, 0x320b5a0, 0xc0006b4300, 0xc000a4d3b0, 0xc0002c0c00, 0x320b5a0, 0xc0006b4300, 0xc000a53200, 0x45d)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1369 +0x158
    github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001800, 0x321bce0, 0xc0004ba900, 0xc0001fc200, 0xc00033b110, 0x4526d40, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:971 +0x470
```

Deleting and recreating the bucket and/or writing a simple bucket-only stack from scratch does not exhibit this issue.

**Comment by ellismg** [comment] 2019-05-15 00:03
Just to check, what are the values of `notFoundPage` and `mainPageSuffix` in this example?

Looking at the source for the upstream terraform provider, it seems like there is an issue there (it's not actually clear to me how a change to "website" could ever actually work, since they seem to have an error where they do not initialize a field of a structure they are populating.

**Comment by lukehoban** [comment] 2019-05-15 13:03
See https://github.com/terraform-providers/terraform-provider-google-beta/pull/706 which is a proposed fix for this issue in the upstream Google Beta Terraform Provider.

**Comment by stack72** [comment] 2019-06-05 16:12
Going to close this out - the upstream PR has been merged and released :)

**Comment by casey-robertson** [comment] 2019-06-05 19:08
Which pulumi provider will this make it into?

**Comment by stack72** [comment] 2019-06-05 19:11
@casey-robertson I believe if you update to the latest release then this should not be an issue anymore - can you try it and see?

**Comment by casey-robertson** [comment] 2019-06-05 22:00
Panic is gone.  However, once set, removing the config or setting to `''` doesn't change anything in the GCP console.  Pulumi sees the change and it shows in the preview, but nothing gets set/updated.

**Comment by casey-robertson** [comment] 2019-06-05 22:22
Here's the config block I pass to the bucket code:

```
 websites: [
                {
                    mainPageSuffix: 'index.html',
                    notFoundPage: 'index.html'
                }
            ]
```

Run `pulumi preview` - no changes as expected.  

```
Previewing update (MINDBODY-Platform/casey-robertson):

     Type                             Name                      Plan     Info
     pulumi:pulumi:Stack              viserion-casey-robertson
 >   ├─ pulumi:pulumi:StackReference  identityStack             read
     ├─ gcp:container:Cluster         local-dev                          1 warning
     ├─ gcp:container:NodePool        k8s-node-pool-private              1 warning
     └─ gcp:container:NodePool        k8s-node-pool-monitoring           1 warning

Diagnostics:
  gcp:container:NodePool (k8s-node-pool-private):
    warning: urn:pulumi:casey-robertson::viserion::gcp:container/nodePool:NodePool::k8s-node-pool-private verification warning: "region": [DEPRECATED] use location instead

  gcp:container:Cluster (local-dev):
    warning: urn:pulumi:casey-robertson::viserion::gcp:container/cluster:Cluster::local-dev verification warning: "region": [DEPRECATED] Use location instead

  gcp:container:NodePool (k8s-node-pool-monitoring):
    warning: urn:pulumi:casey-robertson::viserion::gcp:container/nodePool:NodePool::k8s-node-pool-monitoring verification warning: "region": [DEPRECATED] use location instead

Resources:
    31 unchanged
```

Remove the config block and run `pulumi preview --diff`

```
Previewing update (MINDBODY-Platform/casey-robertson):
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:casey-robertson::viserion::pulumi:pulumi:Stack::viserion-casey-robertson]
    > pulumi:pulumi:StackReference: (read)
        [id=MINDBODY-Platform/rhaegar/casey-robertson]
        [urn=urn:pulumi:casey-robertson::viserion::pulumi:pulumi:StackReference::identityStack]
        name: "MINDBODY-Platform/rhaegar/casey-robertson"
    ~ gcp:storage/bucket:Bucket: (update)
        [id=payments.casey.arcusplatform.io]
        [urn=urn:pulumi:casey-robertson::viserion::gcp:storage/bucket:Bucket::payments.casey.arcusplatform.io]
      - websites: [
      -     [0]: {
              - mainPageSuffix: "index.html"
              - notFoundPage  : "index.html"
            }
        ]
```

Run `pulumi up` and check the GCP console.... index.html is still there for both configs.

**Comment by casey-robertson** [comment] 2019-06-06 20:30
@stack72  ^^

**Comment by lukehoban** [comment] 2019-06-07 00:41
Reopening since it seems there is still perhaps some issue here?

**Comment by stack72** [comment] 2019-06-07 00:56
Hi @casey-robertson 

I will investigate this tomorrow

Paul

**Comment by casey-robertson** [comment] 2019-06-11 16:15
Hi @stack72 - any updates?

**Comment by stack72** [comment] 2019-06-11 16:22
Hi @casey-robertson 	

Can you help me try and figure out this error by giving me a config I can run and recreate it? I know you have posted something above but what do `corsPolicy`, `notFoundPage` and `mainPageSuffix` evaluate to be? I want to try and recreate exactly what the problem you are facing is still

I have a feeling what the problem is but I want to be sure of it before we can try and work out a fix

Thanks in advance

Paul

**Comment by stack72** [comment] 2019-06-19 14:21
@casey-robertson ping :)

**Comment by casey-robertson** [comment] 2019-06-26 19:47
Ok I'll write a minimal program to recreate this.

**Comment by casey-robertson** [comment] 2019-06-26 19:57
index.ts

```
import * as gcp from '@pulumi/gcp';

// Create a GCP resource (Storage Bucket)
export const bucket = new gcp.storage.Bucket('testBucket', {
  name: 'mytestbucketforjson',
  project: 'mindbody-casey-robertson'
});

new gcp.storage.BucketIAMMember(
  'my-bucket-iam',
  {
    bucket: bucket.name,
    member: 'allUsers',
    role: 'roles/storage.objectViewer'
  },
  {
    // Track Pulumi component by attaching to parent.
    // https://pulumi.io/reference/programming-model.html#components
    parent: bucket
  }
);

// Export the DNS name of the bucket
export const bucketName = bucket.url;
```

**Comment by casey-robertson** [comment] 2019-06-26 20:01
this creates a public bucket ^

Now add website values:

```
export const bucket = new gcp.storage.Bucket('testBucket', {
  name: 'mytestbucketforjson',
  project: 'mindbody-casey-robertson',
  websites: [
    {
      notFoundPage: '404.html',
      mainPageSuffix: 'index.html'
    }
  ]
});
```

Pulumi CLI sees that change in the diff and creates the settings:

```
Outputs:
  ~ bucket    : {
        forceDestroy  : false
        id            : "mytestbucketforjson"
        location      : "US"
        name          : "mytestbucketforjson"
        project       : "mindbody-casey-robertson"
        requesterPays : false
        selfLink      : "https://www.googleapis.com/storage/v1/b/mytestbucketforjson"
        storageClass  : "STANDARD"
        url           : "gs://mytestbucketforjson"
        urn           : "urn:pulumi:dev::bucket-test::gcp:storage/bucket:Bucket::testBucket"
      + websites      : [
      +     [0]: {
              + mainPageSuffix: "index.html"
              + notFoundPage  : "404.html"
            }
        ]
    }
    bucketName: "gs://mytestbucketforjson"

Resources:
    ~ 1 updated
    2 unchanged

Duration: 2s
```

Reflected in `gsutil`:

```
 gsutil web get gs://mytestbucketforjson
{"mainPageSuffix": "index.html", "notFoundPage": "404.html"}
```

Now remove those settings.  I tried it two ways, change the values to `' '` and then 2nd, delete the entire code block so it's back to original.

```
Previewing update (dev):

     Type                   Name             Plan       Info
     pulumi:pulumi:Stack    bucket-test-dev
 ~   └─ gcp:storage:Bucket  testBucket       update     [diff: -websites]

Resources:
    ~ 1 to update
    2 unchanged

Updating (dev):

     Type                   Name             Status      Info
     pulumi:pulumi:Stack    bucket-test-dev
 ~   └─ gcp:storage:Bucket  testBucket       updated     [diff: -websites]

Outputs:
  ~ bucket    : {
        forceDestroy  : false
        id            : "mytestbucketforjson"
        location      : "US"
        name          : "mytestbucketforjson"
        project       : "mindbody-casey-robertson"
        requesterPays : false
        selfLink      : "https://www.googleapis.com/storage/v1/b/mytestbucketforjson"
        storageClass  : "STANDARD"
        url           : "gs://mytestbucketforjson"
        urn           : "urn:pulumi:dev::bucket-test::gcp:storage/bucket:Bucket::testBucket"
      ~ websites      : [
          - [0]: {
                }
        ]
    }
    bucketName: "gs://mytestbucketforjson"

Resources:
    ~ 1 updated
    2 unchanged

Duration: 2s
```

Query with gsutil again:

```
 gsutil web get gs://mytestbucketforjson
{"mainPageSuffix": "index.html", "notFoundPage": "404.html"}
```

Setting has not changed per Google's CLI tool.

**Comment by casey-robertson** [comment] 2019-06-26 20:03
Didn't add a `corsPolicy` to keep the test simpler.

**Comment by stack72** [comment] 2019-06-26 23:00
Thanks @casey-robertson - I will try and recreate it and work out what is happening

**Comment by casey-robertson** [comment] 2019-07-03 20:18
Checking in - thanks!

**Comment by casey-robertson** [comment] 2019-07-10 16:45
Ping

**Comment by stack72** [comment] 2019-07-19 18:55
Hi @casey-robertson

I tried to ping you on the community slack about this with a potential suggestion that this has been fixed - thoughts?

P.

**Comment by casey-robertson** [comment] 2019-07-24 15:53
Left on vacation the day you posted this.  Will check now.

**Comment by stack72** [comment] 2019-07-31 14:11
Hi @casey-robertson 	

Ping on this

Paul

**Comment by stack72** [comment] 2019-08-02 14:56
Hi @casey-robertson 	

I am going to close this out - if you still have the issue, then please let me know and we can look through it again

Paul

**Closed by stack72** 2019-08-02 14:56 UTC
Labels: customer/feedback, kind/bug

**Comment by casey-robertson** [comment] 2019-08-06 17:32
Finally reconnected with Paul - still investigating.
