### ISSUE TITLE
Provider is removing roles from Pulumi and non-Pulumi-managed accounts

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi-gcp#118] opened 2019-03-29 22:03 UTC
From the community slack:

> In prototyping I am tearing down app and infrastructure (cluster, db) stacks, but leaving up the identity stack (gcp).  It seems roles are disappearing from BOTH pulumi related gcp service accounts, and NON-pulumi related service accounts.  We have not seen this issue prior to pulumi and so I am correlating it with my activity in the same gcp project.

https://gist.github.com/rosskevin/00f05766829a9b45888c508949399f0a

> One [role assignment] was pulumi, one was:

```
gcloud iam service-accounts create ${BUILD_SA} \
    --project=${GOOGLE_CLOUD_PROJECT} \
    --display-name ${BUILD_SA}

gcloud projects add-iam-policy-binding ${GOOGLE_CLOUD_PROJECT} \
    --role roles/storage.admin \
    --member serviceAccount:${BUILD_SA_EMAIL}
```

**Comment by rosskevin** [comment] 2019-03-29 22:15
Observations:
- it always occurs with a service account that targets a single role `roles/storage.admin`
- it affects pulumi, or non-pulumi service accounts without an identified pattern
- it does appear correlated to my prototyping in a separate cluster but same gcp project
- all service accounts for pulumi are independent of the current production service accounts

From a set of stacks (identity, infrastructure, app) that were up with verified roles, I `destroy`ed each and rechecked roles, still there.  Left the `identity` stack in place.

From existing identity stack, `up`ped `identity` and `app` stacks, roles still good.

Continued prototyping more deployment/service/ingress (which had failures) and eventually found that a non-pulumi sa had the role missing again.

Unfortunately I could never narrow this further and cause it to happen.

**Comment by rosskevin** [comment] 2019-04-02 22:02
Another observation.  The following was created with two roles:

```
export const ciApp = new Identity(
  'ciApp',
  {
    project,
    iamRoles: [
      // for deploying new services/deployments
      'roles/container.developer',
      // for pushing new images to gcr
      'roles/storage.admin',
    ],
  },
  { protect },
)
```

We found  non-pulumi iam had lost `roles/storage.admin` and found a pulumi managed iam had lost only `roles/storage.admin`:

![IAM_–_IAM___admin_–_advisorintake_–_Google_Cloud_Platform](https://user-images.githubusercontent.com/136564/55439044-f52f7a80-5568-11e9-811d-f7ae13fdce27.gif)

So it is something specific to `roles/storage.admin` or so it seems.

**Comment by rosskevin** [comment] 2019-04-02 22:05
Title should change

```diff
- Provider is removing roles from non-Pulumi-managed accounts
+ Provider is removing roles from Pulumi and non-Pulumi-managed accounts
```

**Comment by lukehoban** [comment] 2019-08-02 23:54
@jen20 were you able to reproduce this?  I don’t believe we’ve seen this again since the initial reports, and I’m not exactly sure how to reproduce or diagnose further.

**Comment by lukehoban** [comment] 2019-08-19 22:58
We haven't been able to reproduce this and haven't seen any other reports of this.  If it is possible for this to happen, it is almost certainly an issue in the upstream provider, and we're love to try and pinpoint that issue and report/fix it upstream, but have not been able to due to the inability to reproduce.  Closing out - but if anyone sees this and can share a reproduction - happy to re-open.

**Closed by lukehoban** 2019-08-19 22:58 UTC
