### ISSUE TITLE
AppEngine standard `version.basic_scaling.max_instances` is capped at 20

### ISSUE THREAD

**Issue by xSAVIKx** [pulumi/pulumi-gcp#942] opened 2022-11-08 13:32 UTC
### What happened?

While trying to set the `max_instances` to 64 (upper limit is 200 as per the docs).

### Steps to reproduce

```
gcp.appengine.StandardAppVersionBasicScalingArgs(
    max_instances=64
)
```

### Expected Behavior

The version is deployed with 64 max instances.

### Actual Behavior

```
 Diagnostics:
    gcp:appengine:StandardAppVersion (<service-name>):
      error: 1 error occurred:
      	* Error creating StandardAppVersion: googleapi: Error 400: version.basic_scaling.max_instances (64.0) must be in the range [1.0, 25.0].
      Details:
      [
        ***
          "@type": "type.googleapis.com/google.rpc.BadRequest",
          "fieldViolations": [
            ***
              "description": "version.basic_scaling.max_instances (64.0) must be in the range [1.0, 25.0].",
              "field": "version.basic_scaling.max_instances"
            ***
          ]
        ***
      ]
```

### Output of `pulumi about`

CLI Version      3.46.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME    VERSION
docker  3.5.0
gcp     6.41.0
python  unknown

Host
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.10.5

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by xSAVIKx** [comment] 2022-11-08 14:39
OK, looks like this is an issue in the docs/expectations.

See https://cloud.google.com/appengine/docs/standard/an-overview-of-app-engine#instances

![image](https://user-images.githubusercontent.com/5675689/200593322-06eea249-7f8a-4f67-be4b-4f1d9774f998.png)


So `200` is only valid for `us-central1` region (I was doing a deployment in EU), but docs just mention `200`.

**Comment by squaremo** [comment] 2022-11-10 11:34
Thanks for posting this, then following up! At your suggestion, I've made a PR to link to the instance limits table from the relevant fields in the API docs. I'm going to close this issue as "by design", since it was about the expectation set (which was misleading, hence the docs fix) rather than how it worked.

**Closed by squaremo** 2022-11-10 11:34 UTC
Labels: kind/bug, resolution/by-design
