### ISSUE TITLE
Google Cloud Run - Always reports changes on volume mounts

### ISSUE THREAD

**Issue by atrauzzi** [pulumi/pulumi-gcp#1093] opened 2023-06-01 08:23 UTC
### What happened?

Whenever I re-run `pulumi up` without making any changes, the V2 Cloud Run provider will generate this diff:

```
~ template: {
          ~ containers: [
              ~ [0]: {
                      - volumeMounts: [
                      -     [0]: {
                              - mountPath: "/cloudsql"
                              - name     : "cloudsql"
                            }
                        ]
                    }
            ]
        }
```

This happens despite me having made no changes to my CloudSQL connector setup.

### Expected Behavior

No changes to be generated.

### Steps to reproduce

Set up a Cloud Run service with an SQL connector and run it twice.

### Output of `pulumi about`

```
CLI          
Version      3.68.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME    VERSION
dotnet  unknown
gcp     6.56.0
random  4.13.2

Host     
OS       fedora
Version  38
Arch     x86_64

This project is written in dotnet: executable='/usr/bin/dotnet' version='7.0.105'

Backend        
Name         REDACTED
URL            REDACTED
User           REDACTED
Organizations  

Dependencies:
NAME           VERSION
Pulumi         3.55.1
Pulumi.Gcp     6.56.0
Pulumi.Random  4.13.2

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment] 2023-06-02 19:08
Hi @atrauzzi,

As Robbie mentioned earlier, it would be immensely helpful if you could provide us with a code sample that we can replicate. This would not only assist us in identifying any potential configuration issues in your Pulumi code but also help us pinpoint the root cause of the problem.

Based on my initial investigation using the example code for [spinning up a Cloud Run v2 Service with Cloud SQL](https://www.pulumi.com/registry/packages/gcp/api-docs/cloudrunv2/service/#cloudrunv2-service-sql), it seems that including the volume mount in your Pulumi code might be necessary. It appears that GCP overrides the template and includes the volume mounts because they are required for interacting with Cloud SQL from Cloud Run. Consequently, there will be an actuation fight between the configuration applied/reported by GCP and the one you have locally, leading to a conflict when re-running `pulumi up`.

To resolve this conflict between Pulumi and GCP, you have a couple of options. One approach is to explicitly include the volume mount within your Pulumi program. Alternatively, you can make use of the [ignoreChanges field in the resource configuration](https://www.pulumi.com/docs/concepts/options/ignorechanges/) to prevent diffing on the volume mount field.

Let me know if either of these approaches help.

**Comment by mikhailshilkov** [comment] 2023-07-28 12:23
It vaguely sounds like @atrauzzi found a solution or isn't blocked on this anymore. Since we don't have a repro, I'll err on the side of cleaning things up and close the issue. Please open a new one with a repro if the problem persists and you think it's a bug on Pulumi side.

**Closed by mikhailshilkov** 2023-07-28 12:23 UTC
Labels: kind/bug, resolution/no-repro, awaiting-feedback

**Comment by snamber** [comment] 2023-09-20 09:34
Creating a whole new Pulumi project just to report a bug can be a lot of work, if you don't do it all the time, like yourself.
The reproduction steps are right there: "Set up a Cloud Run Gen2 service with an SQL connector and run it twice."

@atrauzzi is not alone in this issue, together with https://github.com/pulumi/pulumi/issues/9830 this is impossible debug, and workarounds like just ignoring volume field updates would be replicating in code exactly the reason why we don't use UIs – where we forget to update dependencies or changes – and use IaC in the first place.

Pulumi is wonderful and works well mostly, but ignoring issues like these is going to add up.

```
    ~ template: {
          ~ containers: [
              ~ [0]: {
                      ~ volumeMounts: [
                          ~ [0]: {
                                  - mountPath: [secret]
                                  - name     : [secret]
                                }
                        ]
                    }
            ]
        }
```

**Comment by snamber** [comment] 2023-09-20 09:49
@mikhailshilkov can you elaborate on "One approach is to explicitly include the volume mount within your Pulumi program."

I am currently creating cloud instance volumes for the Gen2 Cloud Run instance like this:
```
        volumes = []
        if self.cloud_sql_instance is not None:
            volumes.append(
                cr2.ServiceTemplateVolumeArgs(
                    name="cloudsql",
                    # googleapi: Cloud SQL volume must be named 'cloudsql', and 'cloudsql' is reserved for
                    # Cloud SQL volumes.
                    cloud_sql_instance=cr2.ServiceTemplateVolumeCloudSqlInstanceArgs(
                        instances=[self.cloud_sql_instance.connection_name]
                    )
                )
            )
```
Nothing is set up through the UI. I would call that "explicitly including the volume mount within my Pulumi program", yet still it keeps showing up as a change everytime we re-apply `pulumi up`, even if nothing changed at all, in the configuration.

Would appreciate your support.

**Comment by snamber** [comment] 2023-09-20 12:41
Okay after lunch and a meeting I see the issue (documenting here for the unlucky soul that runs into the same issue), three things are coming together:

- The template has a `volumes` field, that everyone sets correctly like this

```python
cr2.ServiceTemplateVolumeArgs(
    name="cloudsql",
    # googleapi: Cloud SQL volume must be named 'cloudsql', and 'cloudsql' is reserved for
    # Cloud SQL volumes.
    cloud_sql_instance=cr2.ServiceTemplateVolumeCloudSqlInstanceArgs(
        instances=[self.cloud_sql_instance.connection_name]
    )
)
```

- The container definition itself though also has a similarly named `volume_mounts` field; For Cloud SQL the database is connected via a socket, that is mounted here as a volume mount. That mount happens automagically, and people forget to add it in their definition. Name and mount path are always as below.

```python
cr2.ServiceTemplateContainerVolumeMountArgs(
    name="cloudsql",
    mount_path="/cloudsql",
)
```

- @mikhailshilkov, though helpful, talks about adding the volume_mount as a "workaround" which immediately turns off the reader. Adding the mount is not a workaround, it is actually just a mapping of what's happening automatically, to Pulumi's stack; it's the actual solution, not a workaround.

So all in all the working solution for me is – when using Cloud SQL with Cloud Run Gen2 – to just define both at the same time

```python
volumes = []
container_volume_mounts = []
if self.cloud_sql_instance is not None:
    volumes.append(
        cr2.ServiceTemplateVolumeArgs(
            name="cloudsql",
            # googleapi: Cloud SQL volume must be named 'cloudsql', and 'cloudsql' is reserved for
            # Cloud SQL volumes.
            cloud_sql_instance=cr2.ServiceTemplateVolumeCloudSqlInstanceArgs(
                instances=[self.cloud_sql_instance.connection_name]
            )
        )
    )
    container_volume_mounts.append(
        cr2.ServiceTemplateContainerVolumeMountArgs(
            name="cloudsql",
            mount_path="/cloudsql",
        )
    )
```
