### ISSUE TITLE
Deploying new revisions of Cloud Run resources yields 409: Conflict

### ISSUE THREAD

**Issue by floyd-may** [pulumi/pulumi-gcp#350] opened 2020-05-20 20:10 UTC
Deploying new revisions of Cloud Run resources is failing due to the GCP API giving an error response of 409: Conflict. This occurs whether or not the `AutoGenerateRevisionName` field is set (as mentioned by this Terraform provider issue: https://github.com/terraform-providers/terraform-provider-google/issues/5898). I've tried `AutoGenerateRevisionName` and manually generating a random name as well.

**Comment by floyd-may** [comment] 2020-05-21 14:05
@stack72 Get with me on the Slack org to set up a video call if you'd like me to walk you through what I'm experiencing.

**Comment by jaxxstorm** [comment] 2020-05-21 15:37
Can you post the code you're using to deploy so we can try repro this?

**Comment by floyd-may** [comment] 2020-05-21 15:44
You bet -
```csharp
var svc = new cloudrun.Service("my-service-name", new cloudrun.ServiceArgs
{
    Name = "my-service-name",
    Traffics = new InputList<cloudrun.Inputs.ServiceTrafficArgs>
    {
        new cloudrun.Inputs.ServiceTrafficArgs
        {
            LatestRevision = true,
            Percent = 100
        }
    },
    Template = new cloudrun.Inputs.ServiceTemplateArgs
    {
        Spec = new cloudrun.Inputs.ServiceTemplateSpecArgs
        {
            Containers = new InputList<cloudrun.Inputs.ServiceTemplateSpecContainerArgs> {
                new cloudrun.Inputs.ServiceTemplateSpecContainerArgs {
                    Image = DockerImage, // a gcr.io docker image URL
                    Envs = new InputList<cloudrun.Inputs.ServiceTemplateSpecContainerEnvArgs> {
                        new cloudrun.Inputs.ServiceTemplateSpecContainerEnvArgs
                        {
                            Name = "Authentication__Google__ClientId",
                            Value = GoogleOauthClientId
                        },
                        new cloudrun.Inputs.ServiceTemplateSpecContainerEnvArgs
                        {
                            Name = "Authentication__AzureAD__ClientId",
                            Value = AzureOauthClientId
                        },
                        new cloudrun.Inputs.ServiceTemplateSpecContainerEnvArgs
                        {
                            Name = "Authentication__AzureAD__TenantId",
                            Value = AzureOauthTenantId
                        },
                    }
                }
            },
            ContainerConcurrency = 1,
        },
    },
    Location = "us-central1",
    AutogenerateRevisionName = true
});
```

**Comment by Sytten** [comment] 2020-05-21 19:36
I am also having this issue, it happens when you modify something only and then try to modify it in pulumi. The strange thing is that now my stack is corrupted because pulumi thinks it successfully apply the change. 
It seems like the update is not polling first the latest revision before trying to upgrade it.

**Comment by Sytten** [comment] 2020-05-21 19:47
Also I tried deleting the service in GCP and pulumi simply did not detect that the service was gone... I would have expected it to try to recreate it.

**Comment by Sytten** [comment] 2020-05-21 20:25
Edit: I tried doing pure terraform and I don't see this problem, so this is a problem of Pulumi not using the provider correctly and not fetching the latest resource.

**Comment by floyd-may** [comment] 2020-05-21 20:35
I wonder if it has to do with Terraform's concept of "virtual fields". I searched for "virtual" in the codebase (both the GCP provider and core Pulumi) and didn't find much.

**Comment by lukehoban** [comment] 2020-05-21 21:40
> Edit: I tried doing pure terraform and I don't see this problem, so this is a problem of Pulumi not using the provider correctly and not fetching the latest resource.

One key thing that is different by default between Pulumi and Terraform is that Terraform does a "refresh" by default (but can opt-out), and Pulumi does not (but can opt-in).  It may be that the Cloud Run resource was designed to *require* having a refresh done prior to being updated?  

Can you try running `pulumi refresh` and the retrying the `pulumi up` and see if that works?

In general it is a "bug" in a provider if it cannot be used correctly without a refresh - as users can and often do opt-out of refresh by default in Terraform as well - but there may be cases where it is unavoidable.

Note that we are considering changing this default in https://github.com/pulumi/pulumi/issues/2247.

**Comment by floyd-may** [comment] 2020-05-21 21:51
Doing a refresh worked once, but when I added `pulumi refresh --yes` to my CD script prior to `pulumi up --yes` it failed again with a 409, so I think there's something else at play here as well. Are there any considerations I should weigh (other than it takes longer to refresh then deploy) when adding `pulumi refresh --yes` to my CD scripts?

**Comment by kaisellgren** [comment] 2020-05-25 20:54
I have this exact same issue (409).
```ts
return new gcp.cloudrun.Service(
    `${prefix}-app`,
    {
      name: `${prefix}-app`,
      location,
      template: {
        spec: {
          containers: [
            {
              image: imageUrl,
              envs: [
                {
                  name: 'PUBLIC_BUCKET_URL',
                  value: publicBucketName,
                },
              ],
              resources: {
                requests: {
                  memory: '64Mi',
                  cpu: '200m',
                },
                limits: {
                  memory: '256Mi',
                  cpu: '1000m',
                },
              },
            },
          ],
          containerConcurrency: 80,
        },
      },
    },
    { dependsOn: enableCloudRun },
  )
```

When I try to add a new env variable and run `pulumi up` it fails to update with:

```
Diagnostics:
  gcp:cloudrun:Service (x-dev-app):
    error: 1 error occurred:
        * updating urn:pulumi:dev::x::gcp:cloudrun/service:Service::x-dev-app: Error updating Service "locations/europe-north1/namespaces/x/services/x-dev-app": googleapi: Error 409: Revision named 'x-dev-app-00022-jot' with different configuration already exists.
```

If I add this:
```
      autogenerateRevisionName: true,
```

and run `pulumi up`:

```
Diagnostics:
  gcp:cloudrun:Service (x-dev-app):
    error: 1 error occurred:
        * updating urn:pulumi:dev::x::gcp:cloudrun/service:Service::x-dev-app: Error updating Service "locations/europe-north1/namespaces/x/services/x-dev-app": googleapi: Error 409: Conflict for resource 'x-dev-app' for version 'xxx'.
```

Running `pulumi refresh` will take a moment to update the state, but ultimately it has no effect on this issue and the issue continues to persist.

**Comment by floyd-may** [comment] 2020-05-27 14:02
Any update on this @jaxxstorm?

**Comment by leezen** [comment] 2020-05-29 17:43
We're taking a look. It'd be helpful if anyone running into this is able to post detailed logs (https://www.pulumi.com/docs/troubleshooting/#verbose-logging) from running `pulumi refresh` when updating state and what `pulumi refresh` shows in its diff.

**Comment by floyd-may** [comment] 2020-05-29 17:58
Hi @leezen. I'm glad to provide logs. With the verbosity turned all the way up, will the logs contain secrets or other sensitive information that shouldn't be public?

**Comment by Sytten** [comment] 2020-05-29 18:13
I will do that this weekend. yes it will contain sensitive stuff @floyd-may. Can you provide an email so we could send it to you securely @leezen thanks!

**Comment by leezen** [comment] 2020-05-29 18:17
Yes, if you don't want to clean it, can you please DM to me on slack.pulumi.com? Alternative, lee@ via email works, too.

**Comment by jaxxstorm** [comment] 2020-07-01 17:56
We believe this is now resolved with some upstream changes to the terraform provider. If anyone else has this problem, feel free to reopen

**Comment by Sytten** [comment] 2020-07-01 20:31
I will test and confirm, can you link the issue/pr of the upstream provider for posterity @jaxxstorm? thanks!

**Comment by jonsherrard** [comment] 2020-07-29 14:12
I've had this issue in the past, and everything's been fine for a while.

It's just started happening again.

The only thing I can think of is that during the process a Cloud Function failed to deploy, (issue with the resource reference), which failed the process. I am then getting to a partially deployed state that causes the errors in Cloud Run world?

```
googleapi: Error 409: Conflict for resource 'redacted-41a830d': version '1595922945261662' was specified but current version is '1595922945369000'.
```

**Comment by kaisellgren** [comment] 2020-07-29 20:43
Does a `pulumi refresh` help or is it stuck in this conflict state?

**Comment by idoshamun** [comment] 2020-11-02 13:53
refresh worked for me!

**Comment by Sytten** [comment] 2020-11-02 15:54
Refresh usually works yes

**Comment by OliverHGray** [comment] 2021-03-15 20:00
How can this issue be fixed when a `refresh` doesn't help? The problem I'm having is the service has been manually deployed and it doesn't seem to be able to come back under Pulumi control.

I've tried refreshing, setting the revision name explicitly and also exporting the stack configuration and removing occurences the offending revision name from the `inputs` section. None of which is helping matters.

I'm also interested to know why Pulumi (although I guess it's probably Terraform) even tries to upgrade using the current revision name? Won't that always fail?

**Comment by floyd-may** [comment] 2021-03-15 20:19
I've been writing Cloud Run resources quite a bit lately and haven't seen any issues. My guess is that your mix of manual and managed deployments is possibly the culprit here.

**Comment by jeduden** [comment] 2021-03-30 14:12
I still have the problem. It doesn't happen always, deploying with '--refresh' helps, however it does make the deployment a lot slower. Is there a better solution ?
Can we force refresh may be just on the cloudrun resource ?

**Comment by xskif** [comment] 2021-07-22 11:09
Same here.
Issue should be reopened.

**Comment by leezen** [comment] 2021-07-22 15:55
> Can we force refresh may be just the cloudrun resource ?

Yes, it's possible to do a targeted refresh with the `-t` option.

**Comment by alexhwoods** [comment] 2024-05-15 03:45
Same thing as @pierskarsenbarg. If container won't start, you can't update it anymore.

Here's my error
```
Error 409: Conflict for resource 'makeswift': version '1715743123779128' was specified but current version is '1715744121398301'.
```

**Comment by alexhwoods** [comment] 2024-05-15 11:39
A `pulumi refresh` does fix it. The Pulumi provider seems to have an expectation that the deployment succeeded

**Comment by daaain** [comment] 2024-06-27 15:53
A simple `pulumi refresh` didn't work for me, but `pulumi refresh -t urn:pulumi:xxx::yyy::gcp:cloudrun/service:Service::zzz` did

**Comment by dipasqualew** [comment] 2024-10-28 00:47
The issue also happens when deploying an image change from outside pulumi, e.g. deploying the infra changes via pulumi, but an update in the image as part of another pipeline.

**Closed** 2024-11-14 11:50 UTC
Labels: kind/bug
