### ISSUE TITLE
Provider update on gcp.dns.ManagedZone after dependency update fails

### ISSUE THREAD

**Issue by neilprosser** [pulumi/pulumi-gcp#1836] opened 2024-03-15 11:11 UTC
### What happened?

We've updated various dependencies on our project which has caused a `provider` update on a `gcp.dns.ManagedZone`.

The update Pulumi wanted to make was:

```
[provider: urn:pulumi:staging::iac-dns-staging::pulumi:providers:gcp::default_6_53_0::a6294003-c92b-4f10-a766-9d686e34657c => urn:pulumi:staging::iac-dns-staging::pulumi:providers:gcp::default_7_14_0::ee93fb0d-5b1c-48b0-9113-9539a5d8fbd2]
```

This is now failing with the following message:

```
error: 1 error occurred:
	* updating urn:pulumi:staging::iac-dns-staging::gcp:dns/managedZone:ManagedZone::atomist-services-zone: 1 error occurred:
	* Error updating ManagedZone "projects/atomist-dns-staging/managedZones/atomist-services": googleapi: Error 400: The field 'entity.managedZone.id' cannot be modified.
More details:
Reason: immutableField, Message: The field 'entity.managedZone.id' cannot be modified.
Reason: immutableField, Message: The field 'entity.managedZone.creationTime' cannot be modified.
```

### Example

* Have old Pulumi dependencies and have a `gcp.dns.ManagedZone`.
* Update the Pulumi dependencies.
* Try to `pulumi update`.
* Get the above error message.

### Output of `pulumi about`

```
CLI
Version      3.110.0
Go Version   go1.22.1
Go Compiler  gc

Plugins
NAME        VERSION
gcp         7.14.0
kubernetes  4.9.1
nodejs      unknown

Host
OS       darwin
Version  14.4
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/opt/node@18/bin/node' version='v18.19.1'

Current Stack: atomisthq/iac-dns-staging/staging

TYPE                                      URN
pulumi:pulumi:Stack                       urn:pulumi:staging::iac-dns-staging::pulumi:pulumi:Stack::iac-dns-staging-staging
pulumi:providers:gcp                      urn:pulumi:staging::iac-dns-staging::pulumi:providers:gcp::default_7_14_0
gcp:projects/service:Service              urn:pulumi:staging::iac-dns-staging::gcp:projects/service:Service::cloudresourcemanager-service
gcp:projects/service:Service              urn:pulumi:staging::iac-dns-staging::gcp:projects/service:Service::dns-service
gcp:projects/service:Service              urn:pulumi:staging::iac-dns-staging::gcp:projects/service:Service::iam-service
gcp:projects/service:Service              urn:pulumi:staging::iac-dns-staging::gcp:projects/service:Service::logging-service
gcp:projects/service:Service              urn:pulumi:staging::iac-dns-staging::gcp:projects/service:Service::monitoring-service
pulumi:providers:pulumi                   urn:pulumi:staging::iac-dns-staging::pulumi:providers:pulumi::default
gcp:projects/iAMCustomRole:IAMCustomRole  urn:pulumi:staging::iac-dns-staging::gcp:projects/iAMCustomRole:IAMCustomRole::cert-manager-operator-custom-role
gcp:projects/iAMCustomRole:IAMCustomRole  urn:pulumi:staging::iac-dns-staging::gcp:projects/iAMCustomRole:IAMCustomRole::external-dns-operator-custom-role
gcp:serviceaccount/account:Account        urn:pulumi:staging::iac-dns-staging::gcp:serviceaccount/account:Account::anecdotes-service-account
gcp:projects/iAMMember:IAMMember          urn:pulumi:staging::iac-dns-staging::gcp:projects/iAMMember:IAMMember::anecdotes-organizations/1018888314659/roles/anecdotes-viewer-binding
gcp:serviceaccount/key:Key                urn:pulumi:staging::iac-dns-staging::gcp:serviceaccount/key:Key::anecdotes-service-account-key
pulumi:pulumi:StackReference              urn:pulumi:staging::iac-dns-staging::pulumi:pulumi:StackReference::atomisthq/iac-internal-integration-staging/staging
gcp:dns/managedZone:ManagedZone           urn:pulumi:staging::iac-dns-staging::gcp:dns/managedZone:ManagedZone::atomist-services-zone
pulumi:pulumi:StackReference              urn:pulumi:staging::iac-dns-staging::pulumi:pulumi:StackReference::atomisthq/iac-internal-staging/staging
pulumi:providers:gcp                      urn:pulumi:staging::iac-dns-staging::pulumi:providers:gcp::default_6_53_0
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-slack-staging-a-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-go-a-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-_ad5265d4c74ea9b249bf2f776677e46f-cname-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-app-staging-a-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-go-aaaa-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-slack-staging-aaaa-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-www-staging-a-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-dso-a-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-dso-aaaa-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-_1968f37088e0e7d817b371a216e87cc6-cname-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-api-staging-aaaa-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-webhook-receiver-a-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-automation-staging-aaaa-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-app-a-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-txt-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-automation-staging-a-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-_f93e84fa1d8d09523a8eeb90f6d454e8-cname-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-webhook-staging-aaaa-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-_ba108df8a46f57df41ad952e39db92d5-cname-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-webhook-staging-a-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-mx-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-api-staging-a-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-docs-a-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-a-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-www-a-record
gcp:dns/recordSet:RecordSet               urn:pulumi:staging::iac-dns-staging::gcp:dns/recordSet:RecordSet::services-atomist-webhook-receiver-aaaa-record
gcp:projects/iAMMember:IAMMember          urn:pulumi:staging::iac-dns-staging::gcp:projects/iAMMember:IAMMember::ext-iac-internal-integration-cert-manager_cert-manager-operator-member
gcp:projects/iAMMember:IAMMember          urn:pulumi:staging::iac-dns-staging::gcp:projects/iAMMember:IAMMember::ext-iac-internal-integration-external-dns_external-dns-operator-member
gcp:projects/iAMMember:IAMMember          urn:pulumi:staging::iac-dns-staging::gcp:projects/iAMMember:IAMMember::ext-iac-internal-external-dns_external-dns-operator-member
gcp:projects/iAMMember:IAMMember          urn:pulumi:staging::iac-dns-staging::gcp:projects/iAMMember:IAMMember::ext-iac-internal-cert-manager_cert-manager-operator-member


Found no pending operations associated with atomisthq/staging

Backend
Name           pulumi.com
URL            https://app.pulumi.com/neilprosser
User           neilprosser
Organizations  neilprosser, atomisthq
Token type     personal

Dependencies:
NAME                              VERSION
eslint-config-prettier            9.1.0
eslint-plugin-prettier            5.1.3
eslint                            8.57.0
@atomisthq/pulumi                 2.1.5
@pulumi/pulumi                    3.110.0
@types/node                       20.11.28
@typescript-eslint/eslint-plugin  7.2.0
@typescript-eslint/parser         7.2.0
prettier                          3.2.5
@pulumi/gcp                       7.14.0
eslint-plugin-simple-import-sort  12.0.0

Pulumi locates its logs in /var/folders/_w/fyfbm87s04bc61qyydzx_tg00000gp/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment] 2024-03-21 17:03
Hi @neilprosser - thank you for filing this issue.

This seems like it is a duplicate of https://github.com/pulumi/pulumi-gcp/issues/1036. Currently, the very unfortunate "workaround" here is to not manage DNS zones with Pulumi.

I will:

- close this issue for now; please feel free to reopen if you believe #1036 is not the same
- raise the visibility of this issue internally and hopefully prioritize this bug.

**Closed by guineveresaenger** 2024-03-21 17:03 UTC
Labels: kind/bug, resolution/duplicate

**Comment by neilprosser** [comment] 2024-03-25 14:47
Thanks @guineveresaenger. I saw that issue when I was browsing before creating this one but totally didn't spot that they were so similar. I think that's fine.

It's a shame to have to work around it in this way but I'll give that a go. Thanks.
