### ISSUE TITLE
gcp.appengine.Application unable to set `servingStatus` on create

### ISSUE THREAD

**Issue by cakoose** [pulumi/pulumi-gcp#636] opened 2021-07-25 06:49 UTC
The types let me do this:

```ts
new gcp.appengine.Application('dummy', {
    locationId: 'us-central',
    servingStatus: 'USER_DISABLED',
});
```

But then I get this error:

```
  gcp:appengine:Application (dummy):
    error: 1 error occurred:
    	* Error creating App Engine application: googleapi: Error 400: Serving status cannot be updated., failedPrecondition
```

Version:
- `@pulumi/gcp`: 5.11.0
- `pulumi version`: v3.8.0

**Comment by mikhailshilkov** [comment] 2023-10-06 15:12
The conversation seems to have converged on everything working about as expected. Since the issue is quite old and got no recent comments, I'll go ahead and close it.

**Closed by mikhailshilkov** 2023-10-06 15:12 UTC
Labels: kind/bug, resolution/no-repro
